<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="pt" xml:lang="pt"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.56">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="ECODATAGEO">

<title>Análise dos Modelos de Detecção</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="produto2_files/libs/clipboard/clipboard.min.js"></script>
<script src="produto2_files/libs/quarto-html/quarto.js"></script>
<script src="produto2_files/libs/quarto-html/popper.min.js"></script>
<script src="produto2_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="produto2_files/libs/quarto-html/anchor.min.js"></script>
<link href="produto2_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="produto2_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="produto2_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="produto2_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="produto2_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="produto2_files/libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="produto2_files/libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="produto2_files/libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Índice</h2>
   
  <ul>
  <li><a href="#introdução" id="toc-introdução" class="nav-link active" data-scroll-target="#introdução"><span class="header-section-number">1</span> Introdução</a></li>
  <li><a href="#matérias-e-métodos" id="toc-matérias-e-métodos" class="nav-link" data-scroll-target="#matérias-e-métodos"><span class="header-section-number">2</span> Matérias e Métodos</a></li>
  <li><a href="#estatística-básica-por-classes" id="toc-estatística-básica-por-classes" class="nav-link" data-scroll-target="#estatística-básica-por-classes"><span class="header-section-number">3</span> Estatística Básica por classes</a>
  <ul class="collapse">
  <li><a href="#corte-raso-cr" id="toc-corte-raso-cr" class="nav-link" data-scroll-target="#corte-raso-cr"><span class="header-section-number">3.1</span> Corte Raso (CR)</a></li>
  <li><a href="#cicatriz-de-queimada-cqf" id="toc-cicatriz-de-queimada-cqf" class="nav-link" data-scroll-target="#cicatriz-de-queimada-cqf"><span class="header-section-number">3.2</span> Cicatriz de Queimada (CQF)</a></li>
  <li><a href="#corte-seletivo-cs" id="toc-corte-seletivo-cs" class="nav-link" data-scroll-target="#corte-seletivo-cs"><span class="header-section-number">3.3</span> Corte Seletivo (CS)</a></li>
  <li><a href="#matriz-de-confusão" id="toc-matriz-de-confusão" class="nav-link" data-scroll-target="#matriz-de-confusão"><span class="header-section-number">3.4</span> Matriz de confusão</a></li>
  </ul></li>
  <li><a href="#procedimentos" id="toc-procedimentos" class="nav-link" data-scroll-target="#procedimentos"><span class="header-section-number">4</span> Procedimentos</a></li>
  <li><a href="#acurácia-por-classe" id="toc-acurácia-por-classe" class="nav-link" data-scroll-target="#acurácia-por-classe"><span class="header-section-number">5</span> Acurácia Por Classe</a>
  <ul class="collapse">
  <li><a href="#desmatamento-com-corte-raso-cr" id="toc-desmatamento-com-corte-raso-cr" class="nav-link" data-scroll-target="#desmatamento-com-corte-raso-cr"><span class="header-section-number">5.1</span> Desmatamento Com Corte Raso (CR)</a></li>
  <li><a href="#cicatriz-de-queimada-cqf-1" id="toc-cicatriz-de-queimada-cqf-1" class="nav-link" data-scroll-target="#cicatriz-de-queimada-cqf-1"><span class="header-section-number">5.2</span> Cicatriz de Queimada (CQF)</a></li>
  <li><a href="#corte-seletivo-desordenado-csd" id="toc-corte-seletivo-desordenado-csd" class="nav-link" data-scroll-target="#corte-seletivo-desordenado-csd"><span class="header-section-number">5.3</span> Corte Seletivo Desordenado (CSD)</a></li>
  <li><a href="#corte-seletivo-geométrico-csg" id="toc-corte-seletivo-geométrico-csg" class="nav-link" data-scroll-target="#corte-seletivo-geométrico-csg"><span class="header-section-number">5.4</span> Corte Seletivo Geométrico (CSG)</a></li>
  </ul></li>
  <li><a href="#acurácia-global" id="toc-acurácia-global" class="nav-link" data-scroll-target="#acurácia-global"><span class="header-section-number">6</span> Acurácia Global</a>
  <ul class="collapse">
  <li><a href="#métricas-de-avaliação-4" id="toc-métricas-de-avaliação-4" class="nav-link" data-scroll-target="#métricas-de-avaliação-4"><span class="header-section-number">6.1</span> Métricas de Avaliação</a></li>
  <li><a href="#métricas-de-sensibilidade-e-especificidade-4" id="toc-métricas-de-sensibilidade-e-especificidade-4" class="nav-link" data-scroll-target="#métricas-de-sensibilidade-e-especificidade-4"><span class="header-section-number">6.2</span> Métricas de Sensibilidade e Especificidade</a></li>
  <li><a href="#conclusão-4" id="toc-conclusão-4" class="nav-link" data-scroll-target="#conclusão-4"><span class="header-section-number">6.3</span> Conclusão</a></li>
  </ul></li>
  <li><a href="#observações" id="toc-observações" class="nav-link" data-scroll-target="#observações"><span class="header-section-number">7</span> Observações</a></li>
  <li><a href="#referências" id="toc-referências" class="nav-link" data-scroll-target="#referências"><span class="header-section-number">8</span> Referências</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Outros formatos</h2><ul><li><a href="produto2.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li><li><a href="produto2.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Análise dos Modelos de Detecção</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Autor</div>
    <div class="quarto-title-meta-contents">
             <p>ECODATAGEO </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introdução" class="level2" data-number="1">
<h2 data-number="1" class="anchored" data-anchor-id="introdução"><span class="header-section-number">1</span> Introdução</h2>
<p>A análise da acurácia entre mapeamentos de diferentes fontes é a metodologia mais comum para estimar as taxas de acerto e erro em produtos cartográficos. Essa abordagem envolve a comparação de um elemento mapeado em uma classe com um resultado ideal. O número e a distribuição dos pixels usados para avaliar o produto gerado em relação aos dados de referência são determinados por técnicas estatísticas (Olofsson et al.&nbsp;2014).</p>
<p>Neste relatório preliminar mostramos a quantidade necessária de pontos amostrais para realizar a análise de acurácia dos dados das atividade de desmatamento no período de 2017 a 2023 para o estado do Pará.</p>
</section>
<section id="matérias-e-métodos" class="level2" data-number="2">
<h2 data-number="2" class="anchored" data-anchor-id="matérias-e-métodos"><span class="header-section-number">2</span> Matérias e Métodos</h2>
<p>As métricas de acurácia seguiram o padrão <a href="https://www.artredd.org/trees/summaries-guidance/">ART/TREES</a>, tendo como guia as recomendações de Adami et al.&nbsp;2012 e de Olofsson et al.&nbsp;2014.</p>
<p>Adotou-se o método de amostragem estratificada, sendo este consistente em calcular a proporção de cada estrato em relação ao total da população e obter uma quantidade de amostras por classe/estrato.</p>
<p>A amostragem foram realizadas com base nas classes dos vetores georreferenciados do Instituto Nacional de Pesquisas Espaciais (INPE), sendo eles o Desmatamento em Tempo Real do Desmatamento (DETER) e do Monitoramento do Desmatamento (PRODES) do estado do Pará, entre os anos de 2017 e 2023.</p>
<p>Os vetores georreferenciados utilizados foram:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] "deter_fire_shp_2017.shp"           "deter_fire_shp_2018.shp"          
 [3] "deter_fire_shp_2019.shp"           "deter_fire_shp_2020.shp"          
 [5] "deter_fire_shp_2021.shp"           "deter_fire_shp_2022.shp"          
 [7] "deter_fire_shp_2023.shp"           "deter_logging_shp_2017.shp"       
 [9] "deter_logging_shp_2018.shp"        "deter_logging_shp_2019.shp"       
[11] "deter_logging_shp_2020.shp"        "deter_logging_shp_2021.shp"       
[13] "deter_logging_shp_2022.shp"        "deter_logging_shp_2023.shp"       
[15] "prodes_deforestation_shp_2017.shp" "prodes_deforestation_shp_2018.shp"
[17] "prodes_deforestation_shp_2019.shp" "prodes_deforestation_shp_2020.shp"
[19] "prodes_deforestation_shp_2021.shp" "prodes_deforestation_shp_2022.shp"
[21] "prodes_deforestation_shp_2023.shp"</code></pre>
</div>
</div>
<p>Com base nestes arquivos as classes de distúrbios utilizadas foram:</p>
<table class="table-striped table-hover caption-top table">
<caption>Classes</caption>
<colgroup>
<col style="width: 31%">
<col style="width: 18%">
<col style="width: 50%">
</colgroup>
<thead>
<tr class="header">
<th>Arquivos INPE</th>
<th>Classe</th>
<th>Equivalente a</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>deter_fire…</td>
<td>fire</td>
<td>Floresta - Incêndios</td>
</tr>
<tr class="even">
<td>deter_logging…</td>
<td>logging</td>
<td>Floresta - Corte seletivo</td>
</tr>
<tr class="odd">
<td>prodes_deforestation…</td>
<td>deforestation</td>
<td>Floresta - Corte raso desordenado</td>
</tr>
</tbody>
</table>
<p>Os vetores estavam com o DATUM WGS 84 e foram convertidos para o DATUM SIRGAS 2000 (ESPG 4674), para que fosse possível realizar o cálculo da área de cada classe de distúrbio.</p>
<div style="page-break-after: always;"></div>
<p>Parte dos cálculos foram realizadas no ambiente de desenvolvimento <a href="https://www.r-project.org/"><em>R</em></a>.</p>
<p>Para a conversão em lote dos vetores foram utilizados as seguintes funções do ambiente <code>R</code>:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Lê os arquivos com final "shp" do diretório de dados</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a>arquivos <span class="ot">&lt;-</span> <span class="fu">list.files</span>(<span class="at">path =</span> <span class="st">"data/"</span>, <span class="at">pattern =</span> <span class="st">".*shp$"</span>)</span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Transforma o vetor com o nomes de arquivos em um vetor nomeado</span></span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">names</span>(arquivos) <span class="ot">&lt;-</span> arquivos </span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Lê os shapefile do diretório (data) e</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a><span class="co"># converte para WGS 84 / UTM 22N = EPSG:32622 </span></span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a>shapes <span class="ot">&lt;-</span> </span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a>  arquivos <span class="sc">|&gt;</span> </span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>  purrr<span class="sc">::</span><span class="fu">map</span>(\(x) sf<span class="sc">::</span><span class="fu">st_transform</span>(sf<span class="sc">::</span><span class="fu">st_read</span>(<span class="fu">paste0</span>(<span class="st">"data/"</span>, x)), <span class="at">crs =</span> <span class="dv">4674</span>)) <span class="sc">|&gt;</span> </span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a>  purrr<span class="sc">::</span><span class="fu">list_rbind</span>(<span class="at">names_to =</span> <span class="st">"classe"</span>) </span></code><button title="Copiar para a área de transferência" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<p>Após a conversão de DATUM, foi calculada a área em hectares e o número de polígonos de cada classe de distúrbio por ano, o resultado pode ser visto na tabela a seguir.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Classe</th>
<th style="text-align: right;">Nº Polígonos</th>
<th style="text-align: right;">Área (ha)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">deforestation_2017</td>
<td style="text-align: right;">31922</td>
<td style="text-align: right;">300985.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">deforestation_2018</td>
<td style="text-align: right;">32556</td>
<td style="text-align: right;">301098.74</td>
</tr>
<tr class="odd">
<td style="text-align: left;">deforestation_2019</td>
<td style="text-align: right;">34302</td>
<td style="text-align: right;">493185.62</td>
</tr>
<tr class="even">
<td style="text-align: left;">deforestation_2020</td>
<td style="text-align: right;">37372</td>
<td style="text-align: right;">514820.53</td>
</tr>
<tr class="odd">
<td style="text-align: left;">deforestation_2021</td>
<td style="text-align: right;">41315</td>
<td style="text-align: right;">572468.60</td>
</tr>
<tr class="even">
<td style="text-align: left;">deforestation_2022</td>
<td style="text-align: right;">31120</td>
<td style="text-align: right;">502550.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">deforestation_2023</td>
<td style="text-align: right;">30813</td>
<td style="text-align: right;">339786.92</td>
</tr>
<tr class="even">
<td style="text-align: left;">fire_2017</td>
<td style="text-align: right;">1664</td>
<td style="text-align: right;">441522.06</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fire_2018</td>
<td style="text-align: right;">3097</td>
<td style="text-align: right;">902263.49</td>
</tr>
<tr class="even">
<td style="text-align: left;">fire_2019</td>
<td style="text-align: right;">285</td>
<td style="text-align: right;">15165.97</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fire_2020</td>
<td style="text-align: right;">1825</td>
<td style="text-align: right;">215509.25</td>
</tr>
<tr class="even">
<td style="text-align: left;">fire_2021</td>
<td style="text-align: right;">2426</td>
<td style="text-align: right;">399476.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">fire_2022</td>
<td style="text-align: right;">572</td>
<td style="text-align: right;">46510.31</td>
</tr>
<tr class="even">
<td style="text-align: left;">logging_2017</td>
<td style="text-align: right;">90</td>
<td style="text-align: right;">41525.83</td>
</tr>
<tr class="odd">
<td style="text-align: left;">logging_2018</td>
<td style="text-align: right;">67</td>
<td style="text-align: right;">42840.49</td>
</tr>
<tr class="even">
<td style="text-align: left;">logging_2019</td>
<td style="text-align: right;">57</td>
<td style="text-align: right;">29519.66</td>
</tr>
<tr class="odd">
<td style="text-align: left;">logging_2020</td>
<td style="text-align: right;">209</td>
<td style="text-align: right;">113373.66</td>
</tr>
<tr class="even">
<td style="text-align: left;">logging_2021</td>
<td style="text-align: right;">308</td>
<td style="text-align: right;">120761.50</td>
</tr>
<tr class="odd">
<td style="text-align: left;">logging_2022</td>
<td style="text-align: right;">228</td>
<td style="text-align: right;">116841.18</td>
</tr>
<tr class="even">
<td style="text-align: left;">logging_2023</td>
<td style="text-align: right;">168</td>
<td style="text-align: right;">99966.30</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>A quantidade de pontos (n) por classe é definida pela fórmula (Adami 2012):</p>
<p><span class="math display">\[\begin{equation}
n = \frac{(Z\alpha/2)^2 \times p \times q}{e^2}
\end{equation}\]</span></p>
<p>Onde:</p>
<p>n = tamanho da amostra</p>
<p><span class="math inline">\(Z(\alpha/2)\)</span> = valor crítico que corresponde ao grau de confiança (99%)</p>
<p>p = proporção populacional de indivíduos que pertence à determinada categoria</p>
<p>q = proporção populacional de indivíduos que não pertence à determinada categoria (1 - p)</p>
<p>e = margem de erro (2,5%)</p>
<p>Ou como definido por Olosson:</p>
<p><span class="math display">\[\begin{equation}
n = (\frac{\Sigma W_{i}S_{i}}{S(\tilde{O})})^2
\end{equation}\]</span></p>
<p>Onde, n = tamanho da amostra,</p>
<p><span class="math inline">\(W_{i}\)</span> área da classe <em>i</em>,</p>
<p><span class="math inline">\(S_{i}\)</span> é o desvio padrão do estrato <em>i</em>, <span class="math inline">\(S_{i} = \sqrt{U{{i}(1 - U_{i})}}\)</span></p>
<p><span class="math inline">\(S(\tilde{O})\)</span> é o erro padrão</p>
<p>Assim, o número de pontos amostrais para cada categoria de distúrbio ficou defina conforme a tabela a seguir</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<thead>
<tr class="header">
<th style="text-align: left;">Classe</th>
<th style="text-align: right;">Nº Polígonos</th>
<th style="text-align: right;">Área (ha)</th>
<th style="text-align: right;">p</th>
<th style="text-align: right;">q</th>
<th style="text-align: right;">Nº Pontos</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">deforestation</td>
<td style="text-align: right;">239400</td>
<td style="text-align: right;">3024895.5</td>
<td style="text-align: right;">0.52</td>
<td style="text-align: right;">0.48</td>
<td style="text-align: right;">2646.53</td>
</tr>
<tr class="even">
<td style="text-align: left;">fire</td>
<td style="text-align: right;">9869</td>
<td style="text-align: right;">2020447.6</td>
<td style="text-align: right;">0.35</td>
<td style="text-align: right;">0.65</td>
<td style="text-align: right;">2411.90</td>
</tr>
<tr class="odd">
<td style="text-align: left;">logging</td>
<td style="text-align: right;">1127</td>
<td style="text-align: right;">564828.6</td>
<td style="text-align: right;">0.10</td>
<td style="text-align: right;">0.90</td>
<td style="text-align: right;">935.23</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="estatística-básica-por-classes" class="level2" data-number="3">
<h2 data-number="3" class="anchored" data-anchor-id="estatística-básica-por-classes"><span class="header-section-number">3</span> Estatística Básica por classes</h2>
<div id="tbl-classes-ano" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-classes-ano-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;1: Número e porcentagem de polígonos por classe/ano. <em>clas_valid</em> = classe definida pelo analista conforme <a href="#tbl-classes" class="quarto-xref">Tabela&nbsp;6</a>. pol = polígonos.
</figcaption>
<div aria-describedby="tbl-classes-ano-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th>class_valid</th>
<th>nº pol 2017</th>
<th>% 2017</th>
<th>nº pol 2018</th>
<th>% 2018</th>
<th>nº pol 2019</th>
<th>% 2019</th>
<th>nº pol 2020</th>
<th>% 2020</th>
<th>nº pol 2021</th>
<th>% 2021</th>
<th>nº pol 2022</th>
<th>% 2022</th>
<th>nº pol 2023</th>
<th>% 2023</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1-true</td>
<td>237</td>
<td>0,683</td>
<td>330</td>
<td>0,631</td>
<td>44</td>
<td>0,71</td>
<td>194</td>
<td>0,61</td>
<td>270</td>
<td>0,74</td>
<td>104</td>
<td>0,684</td>
<td>239</td>
<td>0,601</td>
</tr>
<tr class="even">
<td>1-false</td>
<td>102</td>
<td>0,294</td>
<td>182</td>
<td>0,348</td>
<td>16</td>
<td>0,258</td>
<td>94</td>
<td>0,296</td>
<td>70</td>
<td>0,192</td>
<td>36</td>
<td>0,237</td>
<td>139</td>
<td>0,349</td>
</tr>
<tr class="odd">
<td>0-veg</td>
<td>8</td>
<td>0,023</td>
<td>10</td>
<td>0,019</td>
<td>2</td>
<td>0,032</td>
<td>30</td>
<td>0,094</td>
<td>22</td>
<td>0,06</td>
<td>7</td>
<td>0,046</td>
<td>11</td>
<td>0,028</td>
</tr>
<tr class="even">
<td>2-cs</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0,002</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>3</td>
<td>0,008</td>
<td>5</td>
<td>0,033</td>
<td>9</td>
<td>0,023</td>
</tr>
<tr class="odd">
<td>3-cqf</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>4-outros</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>347</td>
<td>1</td>
<td>523</td>
<td>1</td>
<td>62</td>
<td>1</td>
<td>318</td>
<td>1</td>
<td>365</td>
<td>1</td>
<td>152</td>
<td>1</td>
<td>398</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="corte-raso-cr" class="level3" data-number="3.1">
<h3 data-number="3.1" class="anchored" data-anchor-id="corte-raso-cr"><span class="header-section-number">3.1</span> Corte Raso (CR)</h3>
<div id="tbl-cr-classes-ano" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cr-classes-ano-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;2: Número e porcentagem de polígonos da classe CR por ano. <em>clas_valid</em> = classe definida pelo analista conforme <a href="#tbl-classes" class="quarto-xref">Tabela&nbsp;6</a>. pol = polígonos.
</figcaption>
<div aria-describedby="tbl-cr-classes-ano-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>class_valid</th>
<th>1-true</th>
<th>1-false</th>
<th>0-veg</th>
<th>2-cs</th>
<th>3-cqf</th>
<th>4-outros</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>nº pol 2017</td>
<td>237</td>
<td>102</td>
<td>8</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>347</td>
</tr>
<tr class="even">
<td>nº pol 2018</td>
<td>330</td>
<td>182</td>
<td>10</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>523</td>
</tr>
<tr class="odd">
<td>nº pol 2019</td>
<td>44</td>
<td>16</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>62</td>
</tr>
<tr class="even">
<td>nº pol 2020</td>
<td>194</td>
<td>94</td>
<td>30</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>318</td>
</tr>
<tr class="odd">
<td>nº pol 2021</td>
<td>270</td>
<td>70</td>
<td>22</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>365</td>
</tr>
<tr class="even">
<td>nº pol 2022</td>
<td>104</td>
<td>36</td>
<td>7</td>
<td>5</td>
<td>0</td>
<td>0</td>
<td>152</td>
</tr>
<tr class="odd">
<td>nº pol 2023</td>
<td>239</td>
<td>139</td>
<td>11</td>
<td>9</td>
<td>0</td>
<td>0</td>
<td>398</td>
</tr>
<tr class="even">
<td>TOTAL</td>
<td>1418</td>
<td>639</td>
<td>90</td>
<td>18</td>
<td>0</td>
<td>0</td>
<td>2165</td>
</tr>
<tr class="odd">
<td>% TOTAL</td>
<td>0,654</td>
<td>0,295</td>
<td>0,0415</td>
<td>0,008</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="cicatriz-de-queimada-cqf" class="level3" data-number="3.2">
<h3 data-number="3.2" class="anchored" data-anchor-id="cicatriz-de-queimada-cqf"><span class="header-section-number">3.2</span> Cicatriz de Queimada (CQF)</h3>
<div id="tbl-cqf-classes-ano" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cqf-classes-ano-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;3: Número e porcentagem de polígonos da classe CQF por ano. <em>clas_valid</em> = classe definida pelo analista conforme <a href="#tbl-classes" class="quarto-xref">Tabela&nbsp;6</a>. pol = polígonos.
</figcaption>
<div aria-describedby="tbl-cqf-classes-ano-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>class_valid</th>
<th>3-true</th>
<th>3-false</th>
<th>0-veg</th>
<th>2-cs</th>
<th>1-cr</th>
<th>4-outros</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>nº pol 2017</td>
<td>241</td>
<td>31</td>
<td>33</td>
<td>12</td>
<td>14</td>
<td>1</td>
<td>332</td>
</tr>
<tr class="even">
<td>nº pol 2018</td>
<td>431</td>
<td>0</td>
<td>19</td>
<td>5</td>
<td>59</td>
<td>0</td>
<td>514</td>
</tr>
<tr class="odd">
<td>nº pol 2019</td>
<td>33</td>
<td>0</td>
<td>4</td>
<td>0</td>
<td>15</td>
<td>0</td>
<td>52</td>
</tr>
<tr class="even">
<td>nº pol 2020</td>
<td>231</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>55</td>
<td>3</td>
<td>289</td>
</tr>
<tr class="odd">
<td>nº pol 2021</td>
<td>292</td>
<td>0</td>
<td>2</td>
<td>0</td>
<td>31</td>
<td>2</td>
<td>327</td>
</tr>
<tr class="even">
<td>nº pol 2022</td>
<td>92</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>17</td>
<td>0</td>
<td>110</td>
</tr>
<tr class="odd">
<td>nº pol 2023</td>
<td>121</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>9</td>
<td>0</td>
<td>130</td>
</tr>
<tr class="even">
<td>TOTAL</td>
<td>1441</td>
<td>31</td>
<td>58</td>
<td>18</td>
<td>200</td>
<td>6</td>
<td>1754</td>
</tr>
<tr class="odd">
<td>% TOTAL</td>
<td>0,822</td>
<td>0,018</td>
<td>0,033</td>
<td>0,01</td>
<td>0,114</td>
<td>0,003</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="corte-seletivo-cs" class="level3" data-number="3.3">
<h3 data-number="3.3" class="anchored" data-anchor-id="corte-seletivo-cs"><span class="header-section-number">3.3</span> Corte Seletivo (CS)</h3>
<section id="cs-desordenado" class="level4" data-number="3.3.1">
<h4 data-number="3.3.1" class="anchored" data-anchor-id="cs-desordenado"><span class="header-section-number">3.3.1</span> CS Desordenado</h4>
<div id="tbl-csd-classes-ano" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-csd-classes-ano-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;4: Número e porcentagem de polígonos da classe CSD por ano. <em>clas_valid</em> = classe definida pelo analista conforme <a href="#tbl-classes" class="quarto-xref">Tabela&nbsp;6</a>. pol = polígonos.
</figcaption>
<div aria-describedby="tbl-csd-classes-ano-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>class_valid</th>
<th>2-true</th>
<th>2-false</th>
<th>0-veg</th>
<th>1-cr</th>
<th>3-cqf</th>
<th>4-outros</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>nº pol 2017</td>
<td>6</td>
<td>3</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>10</td>
</tr>
<tr class="even">
<td>nº pol 2018</td>
<td>8</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>8</td>
</tr>
<tr class="odd">
<td>nº pol 2019</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>5</td>
</tr>
<tr class="even">
<td>nº pol 2020</td>
<td>21</td>
<td>5</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>27</td>
</tr>
<tr class="odd">
<td>nº pol 2021</td>
<td>270</td>
<td>70</td>
<td>22</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>365</td>
</tr>
<tr class="even">
<td>nº pol 2022</td>
<td>31</td>
<td>7</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>38</td>
</tr>
<tr class="odd">
<td>nº pol 2023</td>
<td>20</td>
<td>5</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>25</td>
</tr>
<tr class="even">
<td>TOTAL</td>
<td>360</td>
<td>90</td>
<td>24</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>478</td>
</tr>
<tr class="odd">
<td>% TOTAL</td>
<td>0,753</td>
<td>0,188</td>
<td>0,0502</td>
<td>0,008</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="cs-gemétrico" class="level4" data-number="3.3.2">
<h4 data-number="3.3.2" class="anchored" data-anchor-id="cs-gemétrico"><span class="header-section-number">3.3.2</span> CS Gemétrico</h4>
<div id="tbl-csg-classes-ano" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-csg-classes-ano-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;5: Número e porcentagem de polígonos da classe CSG por ano. <em>clas_valid</em> = classe definida pelo analista conforme <a href="#tbl-classes" class="quarto-xref">Tabela&nbsp;6</a>. pol = polígonos.
</figcaption>
<div aria-describedby="tbl-csg-classes-ano-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>class_valid</th>
<th>2-true</th>
<th>2-false</th>
<th>0-veg</th>
<th>1-cr</th>
<th>3-cqf</th>
<th>4-outros</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>nº pol 2017</td>
<td>7</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>7</td>
</tr>
<tr class="even">
<td>nº pol 2018</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>4</td>
</tr>
<tr class="odd">
<td>nº pol 2019</td>
<td>4</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>5</td>
</tr>
<tr class="even">
<td>nº pol 2020</td>
<td>6</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>7</td>
</tr>
<tr class="odd">
<td>nº pol 2021</td>
<td>31</td>
<td>0</td>
<td>0</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>33</td>
</tr>
<tr class="even">
<td>nº pol 2022</td>
<td>9</td>
<td>0</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>11</td>
</tr>
<tr class="odd">
<td>nº pol 2023</td>
<td>8</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>9</td>
</tr>
<tr class="even">
<td>TOTAL</td>
<td>69</td>
<td>3</td>
<td>2</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>76</td>
</tr>
<tr class="odd">
<td>% TOTAL</td>
<td>0,908</td>
<td>0,039</td>
<td>0,026</td>
<td>0,026</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
<section id="matriz-de-confusão" class="level3" data-number="3.4">
<h3 data-number="3.4" class="anchored" data-anchor-id="matriz-de-confusão"><span class="header-section-number">3.4</span> Matriz de confusão</h3>
<p>Os gráficos a seguir são matrizes de confusão gerada pela função <code>caret::confusionMatrix()</code> no ambiente <code>R</code> (r-project.org). A matriz de confusão é usada para avaliar o desempenho de um modelo de classificação, mostrando as contagens de predições corretas e incorretas em relação às classes reais (verdadeira).</p>
<p>O modelo foi analisado através de classificação visual por um analista especialista em geoprocessamento e fotointerpretação….</p>
</section>
</section>
<section id="procedimentos" class="level2" data-number="4">
<h2 data-number="4" class="anchored" data-anchor-id="procedimentos"><span class="header-section-number">4</span> Procedimentos</h2>
<div id="tbl-classes" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-classes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;6: <strong>VALOR NUMÉRICO DAS CLASSES DE VALIDAÇÃO</strong> (coluna <em>clas_valid</em> nas tabelas de atributos dos arquivos vetoriais. *AGUÁ, SOMBRA, NUVENS, VÁRZEA HERBÁCEA, MEANDROS).
</figcaption>
<div aria-describedby="tbl-classes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Classe</th>
<th style="text-align: center;">Valor</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">FLORESTA/VEG NATIVA (VEG)</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">CORTE RASO (CR)</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">CORTE SELETIVO-CS</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">CS DESORDENADO (CSD)</td>
<td style="text-align: center;">2.1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">CS GEOMÉTRICO (CSG)</td>
<td style="text-align: center;">2.2</td>
</tr>
<tr class="even">
<td style="text-align: right;">CICATRIZ DE QUEIMADA FLORESTA (CQF)</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">*OUTROS</td>
<td style="text-align: center;">4</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p><em>clas_valid</em> ➞ este atributo representa a classe definida pelo analista conforme <a href="#tbl-classes" class="quarto-xref">Tabela&nbsp;6</a></p>
<p><em>label</em> ➞ dado <em>boleano</em>, onde FALSE = 0, TRUE = 1. Ou seja, <em>label</em> = 0 CLASSE ORIGINAL DO POLÍGONO ERRADA (falso positivo), e <em>label</em> = 1 POLÍGONO VERDADEIRO.</p>
<p>Por exemplo as combinações:</p>
<p><em>label</em> = 0 e <em>clas_valid</em> = ‘QUALQUER VALOR DIFERENTE DE ZERO (0)’, significa VALIDAÇÃO NEGATIVA, POLÍGONO ORIGINAL = FALSE;</p>
<p>label = 1 e clas_valid = ‘QUALQUER VALOR DIFERENTE DE ZERO (0)’, significa VALIDAÇÃO POSITIVA, POLÍGONO ORIGINAL= TRUE.</p>
<ul>
<li><p>Foi considerado o ano PRODES a pedido do contratante como referencia de ano na avaliação da acurácia 01 de agosto do ano anterior até 31 julho do ano corrido ex desmatamento 2021 compreende os polígonos detectados entre 01/08/2020 até 31/07/2021;</p></li>
<li><p>Quando o polígono (centroide) selecionado para ser validado apresenta mistura de classes foi preenchido o valor do atributo <em>clas_valid</em> que corresponde a classe que possui a maior representatividade em área (&gt;=50%)</p></li>
<li><p>Na validação da classe fogo de 2017 terá a combinação <em>label</em> = 0 &amp; <em>clas_valid</em> = 3, onde a cicatriz de queimada é presente antes de 01/08/2016, portanto deve ser contabilizadas para o ano de 2016, ver <a href="#fig-cqf-false" class="quarto-xref">Figura&nbsp;5</a> e <a href="#fig-cqf-true" class="quarto-xref">Figura&nbsp;6</a>.</p></li>
<li><p>Na validação de corte seletivo a combinação <em>label</em> = 0 &amp; <em>clas_valid</em> = 2, demostra que há o corte seletivo mas ele errou a classe (desordenada ou geométrica), ver <a href="#fig-cs-false" class="quarto-xref">Figura&nbsp;1</a> e <a href="#fig-cs-true" class="quarto-xref">Figura&nbsp;2</a>.</p></li>
<li><p>Na classe de corte seletivo foi sempre considerado true o polígono cuja a cicatriz permaneceu presente no ano da análise, ver <a href="#fig-cs-false" class="quarto-xref">Figura&nbsp;1</a> e <a href="#fig-cs-true" class="quarto-xref">Figura&nbsp;2</a>.</p></li>
<li><p>Na classe de corte seletivo, é difícil separar as classes CSD de CSG (ver <a href="#fig-cs-false" class="quarto-xref">Figura&nbsp;1</a> e <a href="#fig-cs-true" class="quarto-xref">Figura&nbsp;2</a>), pois foi possível identificar áreas (ex: ano de 2021) que mostram uma temporalidade na identificação desta classes, onde no mesmo ano, no mês T0 a classe era CSG, no T1, a classe mostrou-se como CSD (mostrando o provável período de retirada de madeira da área), e no T3 voltou a se CSG (só sendo visível os pátios secundários de exploração). Por isso a importância da data de detecção ser disponibilizada junto com o dado classificado.</p></li>
<li><p>Na análise do desflorestamento aproximadamente 30% dos polígonos falsos(<em>label</em> = 0 &amp; <em>clas_valid</em> = 1), são desmatamentos verdadeiros só que já presentes no ano anterior, ver <a href="#fig-cr-false" class="quarto-xref">Figura&nbsp;3</a> e <a href="#fig-cr-true" class="quarto-xref">Figura&nbsp;4</a>.</p></li>
</ul>
<div id="fig-cs-false" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cs-false-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-false" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-veg-0-19" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-veg-0-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/0_veg_jul_2019.png" class="lightbox" data-gallery="fig-cs-false" title="Figura&nbsp;1&nbsp;(a): VEG = 0. Julho 2019"><img src="images/0_veg_jul_2019.png" class="img-fluid figure-img" data-ref-parent="fig-cs-false"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-veg-0-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) VEG = 0. Julho 2019
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-false" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-veg-0-20" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-veg-0-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/0_veg_jul_2020.png" class="lightbox" data-gallery="fig-cs-false" title="Figura&nbsp;1&nbsp;(b): VEG = 0. Julho 2020"><img src="images/0_veg_jul_2020.png" class="img-fluid figure-img" data-ref-parent="fig-cs-false"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-veg-0-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) VEG = 0. Julho 2020
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-false" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csd-csg-1-19" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csd-csg-1-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/1_csd_para_csg_set_2019.png" class="lightbox" data-gallery="fig-cs-false" title="Figura&nbsp;1&nbsp;(c): CSD = 1 para CSG. Setembro 2019"><img src="images/1_csd_para_csg_set_2019.png" class="img-fluid figure-img" data-ref-parent="fig-cs-false"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csd-csg-1-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) CSD = 1 para CSG. Setembro 2019
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-false" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csd-csg-2-20" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csd-csg-2-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/2_csd_para_csg_set_2020.png" class="lightbox" data-gallery="fig-cs-false" title="Figura&nbsp;1&nbsp;(d): CSD = 2 para CSG. Setembro 2020"><img src="images/2_csd_para_csg_set_2020.png" class="img-fluid figure-img" data-ref-parent="fig-cs-false"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csd-csg-2-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) CSD = 2 para CSG. Setembro 2020
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-false" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csg-csd-2-18" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csg-csd-2-18-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/2_csg_para_csd_out_2018.png" class="lightbox" data-gallery="fig-cs-false" title="Figura&nbsp;1&nbsp;(e): CSG = 2 para CSD. Outubro 2019"><img src="images/2_csg_para_csd_out_2018.png" class="img-fluid figure-img" data-ref-parent="fig-cs-false"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csg-csd-2-18-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(e) CSG = 2 para CSD. Outubro 2019
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cs-false-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;1: Corte Seletivo (CS) FALSE
</figcaption>
</figure>
</div>
<div id="fig-cs-true" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cs-true-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-true" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csd-0-19" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csd-0-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/0_csd_ago_2019.png" class="lightbox" data-gallery="fig-cs-true" title="Figura&nbsp;2&nbsp;(a): CSD = 0. Agosto 2019"><img src="images/0_csd_ago_2019.png" class="img-fluid figure-img" data-ref-parent="fig-cs-true"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csd-0-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) CSD = 0. Agosto 2019
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/0_csd_jul_2020.png" class="img-fluid figure-img"></p>
<figcaption>CSD = 0. Julho 2020</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-true" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csg-1-19" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csg-1-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/1_csg_ago_2019.png" class="lightbox" data-gallery="fig-cs-true" title="Figura&nbsp;2&nbsp;(b): CSG = 1. Agosto 2019"><img src="images/1_csg_ago_2019.png" class="img-fluid figure-img" data-ref-parent="fig-cs-true"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csg-1-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) CSG = 1. Agosto 2019
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-true" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csg-1-20" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csg-1-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/1_csg_jul_2020.png" class="lightbox" data-gallery="fig-cs-true" title="Figura&nbsp;2&nbsp;(c): CSG = 1. Julho 2020"><img src="images/1_csg_jul_2020.png" class="img-fluid figure-img" data-ref-parent="fig-cs-true"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csg-1-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) CSG = 1. Julho 2020
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-true" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csg-2-17" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csg-2-17-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/2_csg_jul_2017.png" class="lightbox" data-gallery="fig-cs-true" title="Figura&nbsp;2&nbsp;(d): CSG = 2. Julho 2017"><img src="images/2_csg_jul_2017.png" class="img-fluid figure-img" data-ref-parent="fig-cs-true"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csg-2-17-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) CSG = 2. Julho 2017
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-true" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csg-2-18" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csg-2-18-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/2_csg_mar_2018.png" class="lightbox" data-gallery="fig-cs-true" title="Figura&nbsp;2&nbsp;(e): CSG = 2. Março 2018"><img src="images/2_csg_mar_2018.png" class="img-fluid figure-img" data-ref-parent="fig-cs-true"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csg-2-18-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(e) CSG = 2. Março 2018
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-true" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csd-3-21" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csd-3-21-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/3_csd_abr_2021.png" class="lightbox" data-gallery="fig-cs-true" title="Figura&nbsp;2&nbsp;(f): CSD = 3. Abril 2021"><img src="images/3_csd_abr_2021.png" class="img-fluid figure-img" data-ref-parent="fig-cs-true"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csd-3-21-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(f) CSD = 3. Abril 2021
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-true" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csd-3-20" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csd-3-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/3_csd_jul_2020.png" class="lightbox" data-gallery="fig-cs-true" title="Figura&nbsp;2&nbsp;(g): CSD = 3. Julho 2020"><img src="images/3_csd_jul_2020.png" class="img-fluid figure-img" data-ref-parent="fig-cs-true"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csd-3-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(g) CSD = 3. Julho 2020
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cs-true-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;2: Corte Seletivo (CS) TRUE
</figcaption>
</figure>
</div>
<div id="fig-cr-false" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cr-false-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_cr_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="CR = 0. Julho 2022"><img src="images/0_cr_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 0. Julho 2022</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_cr_jul_23.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14" title="CR = 0. Julho 2023"><img src="images/0_cr_jul_23.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 0. Julho 2023</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_csd_ago_21.png" class="lightbox" data-gallery="quarto-lightbox-gallery-15" title="CSD = 1. Agosto 2021"><img src="images/1_csd_ago_21.png" class="img-fluid figure-img"></a></p>
<figcaption>CSD = 1. Agosto 2021</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_csd_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-16" title="CSD = 1. Julho 2022"><img src="images/1_csd_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CSD = 1. Julho 2022</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/2_veg_ago_21.png" class="lightbox" data-gallery="quarto-lightbox-gallery-17" title="VEG = 2. Agosto 2021"><img src="images/2_veg_ago_21.png" class="img-fluid figure-img"></a></p>
<figcaption>VEG = 2. Agosto 2021</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/2_veg_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-18" title="VEG = 2. Julho 2022"><img src="images/2_veg_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>VEG = 2. Julho 2022</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/FALSE_cr_ago_17.png" class="lightbox" data-gallery="quarto-lightbox-gallery-19" title="CR FALSE. Agosto 2017"><img src="images/FALSE_cr_ago_17.png" class="img-fluid figure-img"></a></p>
<figcaption>CR FALSE. Agosto 2017</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/FALSE_cr_jul_18.png" class="lightbox" data-gallery="quarto-lightbox-gallery-20" title="CR FALSE. Julho 2018"><img src="images/FALSE_cr_jul_18.png" class="img-fluid figure-img"></a></p>
<figcaption>CR FALSE. Julho 2018</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cr-false-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;3: Desmatamento (CR) FALSE
</figcaption>
</figure>
</div>
<div id="fig-cr-true" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cr-true-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_cr_jul_19.png" class="lightbox" data-gallery="quarto-lightbox-gallery-21" title="CR = 0. Julho 2019"><img src="images/0_cr_jul_19.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 0. Julho 2019</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_cr_jul_20.png" class="lightbox" data-gallery="quarto-lightbox-gallery-22" title="CR = 0. Julho 2020"><img src="images/0_cr_jul_20.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 0. Julho 2020</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_cr_jul_21.png" class="lightbox" data-gallery="quarto-lightbox-gallery-23" title="CR = 1. Julho 2021"><img src="images/1_cr_jul_21.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 1. Julho 2021</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_cr_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-24" title="CR = 1. Julho 2022"><img src="images/1_cr_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 1. Julho 2022</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/2_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-25" title="CR = 2. Julho 2022"><img src="images/2_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 2. Julho 2022</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/2_jul_23.png" class="lightbox" data-gallery="quarto-lightbox-gallery-26" title="CR = 2. Julho 2023"><img src="images/2_jul_23.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 2. Julho 2023</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/3_jul_18.png" class="lightbox" data-gallery="quarto-lightbox-gallery-27" title="CR = 3. Julho 2018"><img src="images/3_jul_18.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 3. Julho 2018</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/3_jul_19.png" class="lightbox" data-gallery="quarto-lightbox-gallery-28" title="CR = 3. Julho 2019"><img src="images/3_jul_19.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 3. Julho 2019</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cr-true-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;4: Desmatamento (CR) TRUE
</figcaption>
</figure>
</div>
<div id="fig-cqf-false" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cqf-false-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_CQF_dez_2015.png" class="lightbox" data-gallery="quarto-lightbox-gallery-29" title="CQF = 0. Dezembro 2015"><img src="images/0_CQF_dez_2015.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 0. Dezembro 2015</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_CQF_jul_2017.png" class="lightbox" data-gallery="quarto-lightbox-gallery-30" title="CQF = 0. Julho 2017"><img src="images/0_CQF_jul_2017.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 0. Julho 2017</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_CQF_set_2016.png" class="lightbox" data-gallery="quarto-lightbox-gallery-31" title="CQF = 0. SEtembro 2016"><img src="images/0_CQF_set_2016.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 0. SEtembro 2016</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_CQF_dez_2015.png" class="lightbox" data-gallery="quarto-lightbox-gallery-32" title="CQF = 1. Dezembro 2015"><img src="images/1_CQF_dez_2015.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 1. Dezembro 2015</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_CQF_out_2016.png" class="lightbox" data-gallery="quarto-lightbox-gallery-33" title="CQF = 1. Outubro 2016"><img src="images/1_CQF_out_2016.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 1. Outubro 2016</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_CQF_dez_2015-01.png" class="lightbox" data-gallery="quarto-lightbox-gallery-34" title="CQF = 1. Dezembro 2015"><img src="images/1_CQF_dez_2015-01.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 1. Dezembro 2015</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/2_veg_jul_2016.png" class="lightbox" data-gallery="quarto-lightbox-gallery-35" title="VEG = 2. Julho 2016"><img src="images/2_veg_jul_2016.png" class="img-fluid figure-img"></a></p>
<figcaption>VEG = 2. Julho 2016</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/2_veg_jul_2017.png" class="lightbox" data-gallery="quarto-lightbox-gallery-36" title="VEG = 2. Julho 2017"><img src="images/2_veg_jul_2017.png" class="img-fluid figure-img"></a></p>
<figcaption>VEG = 2. Julho 2017</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/3_cr_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-37" title="CR = 3. Julho 2022"><img src="images/3_cr_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 3. Julho 2022</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/3_cr_set_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-38" title="CR = 3. Setembro 2022"><img src="images/3_cr_set_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 3. Setembro 2022</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/3_cr_jul_23.png" class="lightbox" data-gallery="quarto-lightbox-gallery-39" title="CR = 3. Julho 2023"><img src="images/3_cr_jul_23.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 3. Julho 2023</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/4_varzea_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-40" title="VARZEA = 4. Julho 2022"><img src="images/4_varzea_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>VARZEA = 4. Julho 2022</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/4_varzea_out_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-41" title="VARZEA = 4. Outubro 2022"><img src="images/4_varzea_out_22.png" class="img-fluid figure-img"></a></p>
<figcaption>VARZEA = 4. Outubro 2022</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/4_varzea_jun_23.png" class="lightbox" data-gallery="quarto-lightbox-gallery-42" title="VARZEA = 4. Junho 2023"><img src="images/4_varzea_jun_23.png" class="img-fluid figure-img"></a></p>
<figcaption>VARZEA = 4. Junho 2023</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/5_nuvem_jul_2016.png" class="lightbox" data-gallery="quarto-lightbox-gallery-43" title="NUVEM = 5. Julho 2016"><img src="images/5_nuvem_jul_2016.png" class="img-fluid figure-img"></a></p>
<figcaption>NUVEM = 5. Julho 2016</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/5_nuvem_juL_2017.png" class="lightbox" data-gallery="quarto-lightbox-gallery-44" title="NUVEM = 5. Julho 2017"><img src="images/5_nuvem_juL_2017.png" class="img-fluid figure-img"></a></p>
<figcaption>NUVEM = 5. Julho 2017</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cqf-false-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;5: Fire FALSE
</figcaption>
</figure>
</div>
<div id="fig-cqf-true" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cqf-true-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/00_cqf_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-45" title="CQF = 00. Julho 2022"><img src="images/00_cqf_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 00. Julho 2022</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/00_cqf_set_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-46" title="CQF = 00. Setembro 2022"><img src="images/00_cqf_set_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 00. Setembro 2022</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/00_cqf_jul_23.png" class="lightbox" data-gallery="quarto-lightbox-gallery-47" title="CQF = 00. Julho 2023"><img src="images/00_cqf_jul_23.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 00. Julho 2023</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_cqf_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-48" title="CQF = 0. Julho 2022"><img src="images/0_cqf_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 0. Julho 2022</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_cqf_set_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-49" title="CQF = 0. Setembro 2022"><img src="images/0_cqf_set_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 0. Setembro 2022</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_cqf_jun_23.png" class="lightbox" data-gallery="quarto-lightbox-gallery-50" title="CQF = 0. Junho 2023"><img src="images/0_cqf_jun_23.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 0. Junho 2023</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_cqf_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-51" title="CQF = 1. Julho 2022"><img src="images/1_cqf_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 1. Julho 2022</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_cqf_set_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-52" title="CQF = 1. Setembro 2022"><img src="images/1_cqf_set_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 1. Setembro 2022</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_cqf_jul_23.png" class="lightbox" data-gallery="quarto-lightbox-gallery-53" title="CQF = 1. Julho 2023"><img src="images/1_cqf_jul_23.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 1. Julho 2023</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cqf-true-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figura&nbsp;6: Fire TRUE
</figcaption>
</figure>
</div>
<div id="tbl-prob-result" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-prob-result-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Tabela&nbsp;7: Terminologia das Incerteza
</figcaption>
<div aria-describedby="tbl-prob-result-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 43%">
<col style="width: 56%">
</colgroup>
<thead>
<tr class="header">
<th>Termo</th>
<th>Probabilidade do Resultado</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Praticamente certo</td>
<td>99-100% de probabilidade</td>
</tr>
<tr class="even">
<td>Muito provável</td>
<td>90-100% de probabilidade</td>
</tr>
<tr class="odd">
<td>Provável</td>
<td>66-100% de probabilidade</td>
</tr>
<tr class="even">
<td>Aproximadamente tão provável quanto não</td>
<td>33 a 66% de probabilidade</td>
</tr>
<tr class="odd">
<td>Improvável</td>
<td>0-33% de probabilidade</td>
</tr>
<tr class="even">
<td>Muito improvável</td>
<td>0-10% de probabilidade</td>
</tr>
<tr class="odd">
<td>Excepcionalmente improvável</td>
<td>0-1% de probabilidade</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="acurácia-por-classe" class="level2" data-number="5">
<h2 data-number="5" class="anchored" data-anchor-id="acurácia-por-classe"><span class="header-section-number">5</span> Acurácia Por Classe</h2>
<section id="desmatamento-com-corte-raso-cr" class="level3" data-number="5.1">
<h3 data-number="5.1" class="anchored" data-anchor-id="desmatamento-com-corte-raso-cr"><span class="header-section-number">5.1</span> Desmatamento Com Corte Raso (CR)</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="produto2_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="interpretação" class="level4" data-number="5.1.1">
<h4 data-number="5.1.1" class="anchored" data-anchor-id="interpretação"><span class="header-section-number">5.1.1</span> Interpretação</h4>
<ul>
<li><strong>Verdadeiros Negativos (VN):</strong> 91 casos foram corretamente classificados como não-desmatamento.</li>
<li><strong>Falsos Positivos (FP):</strong> 655 casos foram incorretamente classificados como desmatamento.</li>
<li><strong>Falsos Negativos (FN):</strong> 1 casos foram incorretamente classificados como não-desmatamento.</li>
<li><strong>Verdadeiros Positivos (VP):</strong> 1418 casos foram corretamente classificados como desmatamento.</li>
</ul>
</section>
<section id="métricas-de-avaliação" class="level4" data-number="5.1.2">
<h4 data-number="5.1.2" class="anchored" data-anchor-id="métricas-de-avaliação"><span class="header-section-number">5.1.2</span> Métricas de Avaliação</h4>
<ul>
<li><p><strong>Acurácia (Accuracy):</strong> 0.697<br>
A acurácia é a proporção de previsões corretas sobre o total de previsões. Neste caso, o modelo tem uma acurácia de 69,7%. Isso significa que, em 69,7% das vezes, o modelo acertou as previsões.</p></li>
<li><p><strong>Intervalo de Confiança (95% CI):</strong> (0.6772, 0.7163)<br>
O intervalo de confiança para a acurácia indica que, com 95% de confiança, a acurácia verdadeira do modelo está entre 67,72% e 71,63%.</p></li>
<li><p><strong>No Information Rate (NIR):</strong> 0.9575<br>
O No Information Rate é a proporção do maior grupo de classe. Aqui, a classe “0” representa 95,75% dos dados. Esse valor representa a acurácia que seria obtida ao sempre prever a classe mais frequente.</p></li>
<li><p><strong>P-Value [Acc &gt; NIR]:</strong> 1<br>
O valor p associado ao teste da hipótese de que a acurácia do modelo é maior que o No Information Rate. Um valor p de 1 indica que não há evidência estatística de que o modelo é melhor do que uma classificação aleatória.</p></li>
<li><p><strong>Kappa:</strong> 0.1531<br>
O Kappa é uma medida que compara a acurácia do modelo com a acurácia esperada por acaso. Um valor de 0,1531 indica um acordo apenas ligeiramente melhor do que o acaso.</p></li>
<li><p><strong>Teste de McNemar (P-Value):</strong> &lt;0.002<br>
O teste de McNemar avalia a simetria de erros do modelo (erros de tipo I vs.&nbsp;erros de tipo II). Um valor p muito pequeno (&lt;2e-16) indica que há uma diferença significativa na taxa de erros de falsos positivos e falsos negativos.</p></li>
</ul>
</section>
<section id="métricas-de-sensibilidade-e-especificidade" class="level4" data-number="5.1.3">
<h4 data-number="5.1.3" class="anchored" data-anchor-id="métricas-de-sensibilidade-e-especificidade"><span class="header-section-number">5.1.3</span> Métricas de Sensibilidade e Especificidade</h4>
<ul>
<li><p><strong>Sensibilidade (Sensitivity):</strong> 0.98913<br>
A sensibilidade, ou taxa de verdadeiros positivos, é a proporção de casos positivos corretamente identificados pelo modelo. Com um valor de 98,91%, o modelo é altamente eficaz em identificar casos de desmatamento (classe 1).</p></li>
<li><p><strong>Especificidade (Specificity):</strong> 0.68403<br>
A especificidade é a proporção de casos negativos corretamente identificados. Com 68,4%, o modelo é moderadamente eficaz em identificar casos sem desmatamento (classe 0).</p></li>
<li><p><strong>Valor Preditivo Positivo (Pos Pred Value):</strong> 0.12198<br>
O valor preditivo positivo indica a proporção de verdadeiros positivos entre todos os casos que foram previstos como positivos. Aqui, apenas 12,2% das previsões de desmatamento são realmente corretas.</p></li>
<li><p><strong>Valor Preditivo Negativo (Neg Pred Value):</strong> 0.99930<br>
O valor preditivo negativo é a proporção de verdadeiros negativos entre todos os casos que foram previstos como negativos. Com 99,93%, o modelo é altamente eficaz em prever corretamente a ausência de desmatamento.</p></li>
<li><p><strong>Prevalência:</strong> 0.04249<br>
A prevalência é a proporção de casos reais positivos na amostra de dados. Apenas 4,25% dos casos são de desmatamento.</p></li>
<li><p><strong>Taxa de Detecção (Detection Rate):</strong> 0.04203<br>
A taxa de detecção é a proporção de casos reais positivos detectados corretamente pelo modelo.</p></li>
<li><p><strong>Prevalência de Detecção (Detection Prevalence):</strong> 0.34457<br>
A prevalência de detecção é a proporção de casos previstos como positivos pelo modelo.</p></li>
<li><p><strong>Acurácia Balanceada (Balanced Accuracy):</strong> 0.83658<br>
A acurácia balanceada é a média da sensibilidade e da especificidade. Com 83,66%, o modelo mostra um desempenho equilibrado entre identificar corretamente casos positivos e negativos.</p></li>
</ul>
</section>
<section id="conclusão" class="level4" data-number="5.1.4">
<h4 data-number="5.1.4" class="anchored" data-anchor-id="conclusão"><span class="header-section-number">5.1.4</span> Conclusão</h4>
<p>O modelo é altamente sensível (bom para detectar desmatamento), mas tem baixa especificidade e valor preditivo positivo, indicando que comete muitos falsos positivos (erros ao prever desmatamento quando não há). A acurácia é moderada e o Kappa sugere que o modelo tem um desempenho apenas ligeiramente melhor que o acaso. Devido ao valor P do teste de McNemar ser muito baixo, existe um viés significativo no tipo de erros cometidos pelo modelo. Em resumo, o modelo pode ser bom para detectar quase todos os casos de desmatamento, mas comete muitos erros ao prever desmatamento onde não existe.</p>
<p><strong>Com este valor de acurácia (69,7%), considera-se que o modelo apresentou um resultado provável de ocorrer (<a href="#tbl-prob-result" class="quarto-xref">Tabela&nbsp;7</a>).</strong></p>
</section>
</section>
<section id="cicatriz-de-queimada-cqf-1" class="level3" data-number="5.2">
<h3 data-number="5.2" class="anchored" data-anchor-id="cicatriz-de-queimada-cqf-1"><span class="header-section-number">5.2</span> Cicatriz de Queimada (CQF)</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="produto2_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="interpretação-1" class="level4" data-number="5.2.1">
<h4 data-number="5.2.1" class="anchored" data-anchor-id="interpretação-1"><span class="header-section-number">5.2.1</span> Interpretação</h4>
<ul>
<li><strong>Verdadeiro Negativo (TN):</strong> 53 casos foram corretamente classificados como não-cicatriz de queimada.</li>
<li><strong>Falso Positivo (FP):</strong> 259 casos foram incorretamente classificados como cicatriz de queimada</li>
<li><strong>Falso Negativo (FN):</strong> 1 casos foram incorretamente classificados como não-cicatriz de queimada.</li>
<li><strong>Verdadeiro Positivo (TP):</strong> 1441 casos foram corretamente classificados como cicatriz de queimada.</li>
</ul>
</section>
<section id="métricas-de-avaliação-1" class="level4" data-number="5.2.2">
<h4 data-number="5.2.2" class="anchored" data-anchor-id="métricas-de-avaliação-1"><span class="header-section-number">5.2.2</span> Métricas de Avaliação</h4>
<ul>
<li><p><strong>Acurácia:</strong> 0.8518 (85.18%)<br>
O modelo tem um desempenho geral bom, com 85.18% de previsões corretas.</p></li>
<li><p><strong>Kappa:</strong> 0.2503<br>
Indica uma leve concordância entre as previsões do modelo e a classificação real, ajustada para a concordância que ocorre por acaso.</p></li>
<li><p><strong>Valor-p do Teste de McNemar:</strong> &lt;0.0002<br>
Mostra uma diferença estatisticamente significativa entre falsos positivos e falsos negativos.</p></li>
</ul>
</section>
<section id="métricas-de-sensibilidade-e-especificidade-1" class="level4" data-number="5.2.3">
<h4 data-number="5.2.3" class="anchored" data-anchor-id="métricas-de-sensibilidade-e-especificidade-1"><span class="header-section-number">5.2.3</span> Métricas de Sensibilidade e Especificidade</h4>
<ul>
<li><p><strong>Sensibilidade:</strong> 0.98148 (98.15%)<br>
O modelo é muito eficaz em detectar cicatrizes de queimadas quando elas realmente estão presentes.</p></li>
<li><p><strong>Especificidade:</strong> 0.84765 (84.77%)<br>
Indica que o modelo é bom em identificar corretamente os casos negativos (sem cicatriz de queimada).</p></li>
<li><p><strong>Valor Preditivo Positivo (PPV):</strong> 0.16987 (16.99%)<br>
A maioria das previsões positivas feitas pelo modelo são falsos positivos, o que indica baixa precisão nas previsões positivas.</p></li>
<li><p><strong>Valor Preditivo Negativo (NPV):</strong> 0.99931 (99.93%)<br>
Altamente confiável quando o modelo prevê a ausência de cicatriz de queimada.</p></li>
<li><p><strong>Prevalência:</strong> 0.03079 (3.08%)<br>
Indica que cicatrizes de queimadas são relativamente raras nos dados.</p></li>
<li><p><strong>Taxa de Detecção:</strong> 0.03022 (3.02%)<br>
Proporção de casos positivos reais detectados corretamente pelo modelo.</p></li>
<li><p><strong>Prevalência de Detecção:</strong> 0.17788 (17.79%)<br>
Proporção de casos previstos como positivos pelo modelo.</p></li>
<li><p><strong>Acurácia Balanceada:</strong> 0.91456 (91.46%)<br>
Média entre Sensibilidade e Especificidade, útil para conjuntos de dados desbalanceados.</p></li>
</ul>
</section>
<section id="conclusão-1" class="level4" data-number="5.2.4">
<h4 data-number="5.2.4" class="anchored" data-anchor-id="conclusão-1"><span class="header-section-number">5.2.4</span> Conclusão</h4>
<p>O modelo é altamente sensível e tem boa acurácia geral, mas a baixa especificidade e o baixo valor preditivo positivo indicam uma tendência a prever falsos positivos. Para melhorar, o modelo pode necessitar de ajustes para aumentar a precisão das previsões positivas, especialmente em um contexto onde falsos positivos podem ter implicações significativas.</p>
<p><strong>Com este valor de acurácia (85,18%), considera-se que o modelo apresentou um resultado provável de ocorrer (<a href="#tbl-prob-result" class="quarto-xref">Tabela&nbsp;7</a>).</strong></p>
</section>
</section>
<section id="corte-seletivo-desordenado-csd" class="level3" data-number="5.3">
<h3 data-number="5.3" class="anchored" data-anchor-id="corte-seletivo-desordenado-csd"><span class="header-section-number">5.3</span> Corte Seletivo Desordenado (CSD)</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="produto2_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="interpretação-2" class="level4" data-number="5.3.1">
<h4 data-number="5.3.1" class="anchored" data-anchor-id="interpretação-2"><span class="header-section-number">5.3.1</span> Interpretação</h4>
<ul>
<li><strong>Verdadeiros Negativos (VN)</strong>: 2 casos foram corretamente classificados como não-corte seletivo.</li>
<li><strong>Falsos Positivos (FP)</strong>: 24 casos foram incorretamente classificados como corte seletivo desordenado.</li>
<li><strong>Falsos Negativos (FN)</strong>: 0 casos foram incorretamente classificados como não-corte seletivo desordenado.</li>
<li><strong>Verdadeiros Positivos (VP)</strong>: 101 ccasos foram corretamente classificados como corte seletivo desordenado.</li>
</ul>
</section>
<section id="métricas-de-avaliação-2" class="level4" data-number="5.3.2">
<h4 data-number="5.3.2" class="anchored" data-anchor-id="métricas-de-avaliação-2"><span class="header-section-number">5.3.2</span> Métricas de avaliação</h4>
<ul>
<li><p><strong>Acurácia</strong>: 0.811 (81.1%)<br>
A acurácia indica a proporção de previsões corretas (tanto ‘0’ quanto ‘1’) sobre o total de previsões. Neste caso, 81.1% das previsões do modelo estão corretas.</p></li>
<li><p><strong>Intervalo de Confiança de 95% para a Acurácia</strong>: (0.732, 0.875)<br>
Este intervalo sugere que há 95% de confiança de que a verdadeira acurácia do modelo está entre 73.2% e 87.5%.</p></li>
<li><p><strong>Taxa de Informação Nula (No Information Rate, NIR)</strong>: 0.9843 (98.43%)<br>
A NIR é a proporção de previsões corretas que seriam feitas se o modelo sempre previsse a classe mais comum. Neste caso, a classe ‘1’ (presença de CSD) é a mais comum.</p></li>
<li><p><strong>P-Valor [Acc &gt; NIR]</strong>: 1<br>
Este valor indica a probabilidade de o modelo ser melhor do que um modelo que sempre prevê a classe mais frequente. Um valor de 1 sugere que o modelo não é significativamente melhor que um modelo ingênuo que sempre prevê a classe majoritária.</p></li>
<li><p><strong>Kappa</strong>: 0.117<br>
O Kappa mede a concordância entre as previsões do modelo e as classificações reais ajustadas para a concordância ao acaso. Um valor de 0.117 indica uma concordância muito baixa além do acaso.</p></li>
<li><p><strong>Teste de McNemar P-Valor</strong>: 0.000002668<br>
O teste de McNemar é usado para avaliar a significância das diferenças entre as duas classificações (predição ‘0’ vs ‘1’). Um p-valor muito baixo indica uma diferença significativa entre as classificações ‘0’ e ‘1’.</p></li>
</ul>
</section>
<section id="métricas-de-sensibilidade-e-especificidade-2" class="level4" data-number="5.3.3">
<h4 data-number="5.3.3" class="anchored" data-anchor-id="métricas-de-sensibilidade-e-especificidade-2"><span class="header-section-number">5.3.3</span> Métricas de Sensibilidade e Especificidade</h4>
<ul>
<li><p><strong>Sensibilidade (Recall para a classe ‘0’)</strong>: 1.00000 (100%)<br>
A sensibilidade indica a capacidade do modelo de prever corretamente a classe ‘0’. Neste caso, o modelo detecta corretamente todos os casos de ‘0’ (ausência de CSD).</p></li>
<li><p><strong>Especificidade (Recall para a classe ‘1’)</strong>: 0.80800 (80.8%)&nbsp; A especificidade indica a capacidade do modelo de prever corretamente a classe ‘1’. Neste caso, 80.8% dos casos de ‘1’ (presença de CSD) são corretamente identificados.</p></li>
<li><p><strong>Valor Preditivo Positivo (PPV ou Precisão para a classe ‘0’)</strong>: 0.07692 (7.692%)<br>
O PPV indica a proporção de previsões ‘0’ que são corretamente ‘0’. Aqui, apenas 7.692% das previsões de ‘0’ são verdadeiras.</p></li>
<li><p><strong>Valor Preditivo Negativo (NPV para a classe ‘1’)</strong>: 1.00000 (100%)&nbsp; O NPV indica a proporção de previsões ‘1’ que são corretamente ‘1’. Neste caso, todas as previsões de ‘1’ estão corretas.</p></li>
<li><p><strong>Prevalência</strong>: 0.01575 (1.575%)&nbsp; A prevalência é a proporção de casos reais da classe ‘0’. Neste conjunto de dados, 1.575% das amostras são da classe ‘0’.</p></li>
<li><p><strong>Taxa de Detecção (Detection Rate para a classe ‘0’)</strong>: 0.01575 (1.575%)&nbsp; A taxa de detecção é a proporção de casos positivos que são corretamente identificados. Coincide com a prevalência aqui.</p></li>
<li><p><strong>Prevalência de Detecção (Detection Prevalence para a classe ‘0’)</strong>: 0.20472 (20.472%)&nbsp; A prevalência de detecção é a proporção de todas as previsões que são para a classe ‘0’. Neste caso, 20.472% das previsões do modelo foram para a classe ‘0’.</p></li>
<li><p><strong>Acurácia Balanceada</strong>: 0.90400 (90.4%)&nbsp; A acurácia balanceada é a média da sensibilidade e especificidade. Reflete a habilidade do modelo em identificar ambas as classes de forma justa. Neste caso, é alta, indicando bom desempenho geral.</p></li>
</ul>
</section>
<section id="conclusão-2" class="level4" data-number="5.3.4">
<h4 data-number="5.3.4" class="anchored" data-anchor-id="conclusão-2"><span class="header-section-number">5.3.4</span> Conclusão</h4>
<p>O modelo apresenta alta acurácia geral (81.1%), mas isso pode ser enganoso devido à distribuição altamente desequilibrada das classes (classe ‘1’ dominante). A alta sensibilidade e valor preditivo negativo sugerem que o modelo é bom em detectar a classe ‘1’ (presença de CSD), mas tem dificuldade significativa em prever corretamente a classe ‘0’ (ausência de CSD), como indicado pela baixa especificidade e valor preditivo positivo. O valor de Kappa baixo também indica que o modelo não tem um desempenho muito melhor do que o acaso quando ajustado para a distribuição de classe.</p>
<p><strong>Com este valor de acurácia (81,1%), considera-se que o modelo apresentou um resultado provável de ocorrer (<a href="#tbl-prob-result" class="quarto-xref">Tabela&nbsp;7</a>).</strong></p>
</section>
</section>
<section id="corte-seletivo-geométrico-csg" class="level3" data-number="5.4">
<h3 data-number="5.4" class="anchored" data-anchor-id="corte-seletivo-geométrico-csg"><span class="header-section-number">5.4</span> Corte Seletivo Geométrico (CSG)</h3>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="produto2_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="interpretação-3" class="level4" data-number="5.4.1">
<h4 data-number="5.4.1" class="anchored" data-anchor-id="interpretação-3"><span class="header-section-number">5.4.1</span> Interpretação</h4>
<ul>
<li><p><strong>Verdadeiro Negativo (VN):</strong> 2 casos foram corretamente classificados como não-corte seletivo geométrico.</p></li>
<li><p><strong>Falso Positivo (FP):</strong> 5 casos foram incorretamente classificados como corte seletivo geométrico.</p></li>
<li><p><strong>Falso Negativo (FN):</strong> 0 casos foram incorretamente classificados como não-corte seletivo geométrico.</p></li>
<li><p><strong>Verdadeiro Positivo (VP):</strong> 69 casos foram corretamente classificados como corte seletivo geométrico.</p></li>
</ul>
</section>
<section id="métricas-de-avaliação-3" class="level4" data-number="5.4.2">
<h4 data-number="5.4.2" class="anchored" data-anchor-id="métricas-de-avaliação-3"><span class="header-section-number">5.4.2</span> Métricas de Avaliação</h4>
<ul>
<li><p><strong>Accuracy (Acurácia):</strong> 0.9342 (93.42%) A acurácia indica a proporção de todas as previsões corretas (VN + VP) em relação ao total de amostras. Neste caso, o modelo classificou corretamente 93.42% dos exemplos.</p></li>
<li><p><strong>95% CI (Intervalo de Confiança de 95% para a Acurácia):</strong> (0.8531, 0.9783)&nbsp; O intervalo de confiança indica a faixa dentro da qual a verdadeira acurácia do modelo está, com 95% de confiança. Isso sugere que a acurácia real do modelo está entre 85.31% e 97.83%.</p></li>
<li><p><strong>No Information Rate (NIR):</strong> 0.9737 (97.37%) O NIR representa a acurácia que seria alcançada se o modelo previsse sempre a classe mais comum (classe 1, corte seletivo, que aparece em 97.37% dos casos).</p></li>
<li><p><strong>P-Value [Acc &gt; NIR]:</strong> 0.98486 Este p-valor testa a hipótese de que a acurácia do modelo é melhor do que o NIR. Um valor de p maior que 0.05 sugere que não há evidência estatística de que o modelo seja melhor do que uma classificação ingênua que sempre prevê a classe mais comum.</p></li>
<li><p><strong>Kappa:</strong> 0.4207 O coeficiente Kappa mede o grau de concordância entre as previsões do modelo e as classificações reais, ajustado para a concordância que ocorreria por acaso. Um valor de 0.4207 indica uma concordância moderada, mas não excelente.</p></li>
<li><p><strong>Mcnemar’s Test P-Value:</strong> 0.07364 O teste de McNemar é utilizado para avaliar se as taxas de erro entre duas classificações são significativamente diferentes. Um p-valor maior que 0.05 indica que não há diferença estatisticamente significativa entre as taxas de erro dos dois grupos.</p></li>
</ul>
</section>
<section id="métricas-de-sensibilidade-e-especificidade-3" class="level4" data-number="5.4.3">
<h4 data-number="5.4.3" class="anchored" data-anchor-id="métricas-de-sensibilidade-e-especificidade-3"><span class="header-section-number">5.4.3</span> Métricas de Sensibilidade e Especificidade</h4>
<ul>
<li><p><strong>Sensitivity (Sensibilidade):</strong> 1.00000 (100%) Sensibilidade é a capacidade do modelo de identificar corretamente os casos positivos (corte seletivo). Uma sensibilidade de 100% indica que o modelo identificou todos os casos de corte seletivo corretamente.</p></li>
<li><p><strong>Specificity (Especificidade):</strong> 0.93243 (93.24%) Especificidade é a capacidade do modelo de identificar corretamente os casos negativos (não-corte seletivo). O valor de 93.24% indica que o modelo foi capaz de identificar corretamente a maioria dos casos de não-corte seletivo.</p></li>
<li><p><strong>Pos Pred Value (Valor Preditivo Positivo):</strong> 0.28571 (28.57%) O valor preditivo positivo representa a proporção de previsões positivas corretas entre todas as previsões positivas. Um valor de 28.57% indica que, entre todas as vezes que o modelo previu um corte seletivo, apenas 28.57% das previsões estavam corretas.</p></li>
<li><p><strong>Neg Pred Value (Valor Preditivo Negativo):</strong> 1.00000 (100%) O valor preditivo negativo representa a proporção de previsões negativas corretas entre todas as previsões negativas. Um valor de 100% indica que todas as previsões de não-corte seletivo estavam corretas.</p></li>
<li><p><strong>Prevalence (Prevalência):</strong> 0.02632 (2.63%) A prevalência indica a proporção de casos positivos reais na população total. Apenas 2.63% dos casos são de corte seletivo.</p></li>
<li><p><strong>Detection Rate (Taxa de Detecção):</strong> 0.02632 (2.63%) A taxa de detecção indica a proporção de casos positivos detectados corretamente pelo modelo.</p></li>
<li><p><strong>Detection Prevalence (Prevalência de Detecção):</strong> 0.09211 (9.21%) A prevalência de detecção indica a proporção de todas as previsões feitas como positivas pelo modelo.</p></li>
<li><p><strong>Balanced Accuracy (Acurácia Balanceada):</strong> 0.96622 (96.62%) A acurácia balanceada é a média da sensibilidade e especificidade. Um valor de 96.62% indica que o modelo tem um bom equilíbrio entre a capacidade de detectar casos positivos e negativos.</p></li>
</ul>
</section>
<section id="conclusão-3" class="level4" data-number="5.4.4">
<h4 data-number="5.4.4" class="anchored" data-anchor-id="conclusão-3"><span class="header-section-number">5.4.4</span> Conclusão</h4>
<pre><code>O modelo mostra uma alta acurácia e sensibilidade, sugerindo que é muito bom em identificar casos de corte seletivo. No entanto, o baixo valor preditivo positivo (28.57%) indica uma alta taxa de falsos positivos, sugerindo que o modelo frequentemente classifica erroneamente os casos como corte seletivo quando não são. O Kappa de 0.4207 sugere uma concordância moderada além do acaso. A especificidade é alta, mas o teste de McNemar e o p-valor para a acurácia em relação ao NIR sugerem que o modelo não é significativamente melhor do que uma classificação baseada na classe majoritária.

**Com esta acurácia (93,42%), considera-se que o modelo apresentou um resultado muito provável de ocorrer (@tbl-prob-result).**</code></pre>
</section>
</section>
</section>
<section id="acurácia-global" class="level2" data-number="6">
<h2 data-number="6" class="anchored" data-anchor-id="acurácia-global"><span class="header-section-number">6</span> Acurácia Global</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="produto2_files/figure-html/acuracia-geral-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>A matriz de confusão mostra como as previsões do modelo se comparam com os valores reais (referência) para cada classe:</p>
<ul>
<li><strong>CQF</strong>: 1441 instâncias foram corretamente classificadas como CQF, enquanto 55 instâncias de VEG foram erroneamente classificadas como CQF.</li>
<li><strong>CR</strong>: 1418 instâncias foram corretamente classificadas como CR, enquanto 862 instâncias de VEG foram erroneamente classificadas como CR.</li>
<li><strong>CSD_1</strong>: 101 instâncias foram corretamente classificadas como CSD_1.</li>
<li><strong>CSG_2</strong>: 69 instâncias foram corretamente classificadas como CSG_2.</li>
<li><strong>VEG</strong>: 148 instâncias foram corretamente classificadas como VEG, mas muitas instâncias (55 para CQF e 862 para CR) foram erroneamente classificadas como outras classes.</li>
</ul>
<section id="métricas-de-avaliação-4" class="level3" data-number="6.1">
<h3 data-number="6.1" class="anchored" data-anchor-id="métricas-de-avaliação-4"><span class="header-section-number">6.1</span> Métricas de Avaliação</h3>
<ul>
<li><strong>Accuracy (Acurácia)</strong>: 0.7707 Isso significa que aproximadamente 77% das previsões do modelo estão corretas.</li>
<li><strong>95% CI (Intervalo de Confiança de 95%)</strong>: (0.7576, 0.7835) Indica que a verdadeira acurácia do modelo está entre 75,76% e 78,35% com 95% de confiança.</li>
<li><strong>No Information Rate (Taxa de Não Informação)</strong>: 0.5531 Representa a proporção da maior classe no conjunto de dados. Se o modelo previsse sempre a classe mais frequente, teria uma acurácia de 55,31%.</li>
<li><strong>P-Value [Acc &gt; NIR]</strong>: &lt; 2.2e-16 Indica que a acurácia do modelo é significativamente maior do que a taxa de não informação, sugerindo que o modelo tem valor preditivo.</li>
<li><strong>Kappa</strong>: 0.6588. Essa métrica considera a acurácia e o acaso. Um valor de 0,6588 indica uma concordância substancial além do acaso.</li>
<li><strong>Mcnemar’s Test P-Value</strong>: NA. Este teste não é aplicável porque o modelo pode não ter condições para o teste, como falta de dados para realizar a comparação de erros tipo I e tipo II.</li>
</ul>
</section>
<section id="métricas-de-sensibilidade-e-especificidade-4" class="level3" data-number="6.2">
<h3 data-number="6.2" class="anchored" data-anchor-id="métricas-de-sensibilidade-e-especificidade-4"><span class="header-section-number">6.2</span> Métricas de Sensibilidade e Especificidade</h3>
<p>Para cada classe, temos várias métricas importantes:</p>
<ul>
<li><strong>Sensitivity (Sensibilidade)</strong>: Capacidade do modelo de identificar corretamente instâncias positivas de uma classe específica.
<ul>
<li><strong>CQF</strong>: 0.9632. O modelo identificou corretamente 96,32% das instâncias CQF.</li>
<li><strong>CR</strong>: 0.6219. O modelo identificou corretamente 62,19% das instâncias CR, o que é relativamente baixo.</li>
<li><strong>CSD_1</strong>: 0.8145. O modelo identificou corretamente 81,45% das instâncias CSD_1.</li>
<li><strong>CSG_2</strong>: 0.9583. O modelo identificou corretamente 95,83% das instâncias CSG_2.</li>
<li><strong>VEG</strong>: 0.9867. O modelo identificou corretamente 98,67% das instâncias VEG.</li>
</ul></li>
<li><strong>Specificity (Especificidade)</strong>: Capacidade do modelo de identificar corretamente instâncias negativas de uma classe específica.
<ul>
<li>Muito alta para todas as classes exceto VEG, onde é de 0.76259.</li>
</ul></li>
<li><strong>Pos Pred Value (Valor Preditivo Positivo)</strong>: Proporção de verdadeiros positivos entre todos os positivos previstos.
<ul>
<li><strong>CQF</strong>: 0.9993. Quase todas as instâncias previstas como CQF são realmente CQF.</li>
<li><strong>VEG</strong>: 0.1357. Apenas 13,57% das instâncias previstas como VEG são realmente VEG, indicando que muitas previsões de VEG estão incorretas.</li>
</ul></li>
<li><strong>Neg Pred Value (Valor Preditivo Negativo)</strong>: Proporção de verdadeiros negativos entre todos os negativos previstos.
<ul>
<li>Geralmente alta, indicando que as instâncias que não são de uma determinada classe são bem identificadas como não pertencentes a essa classe.</li>
</ul></li>
<li><strong>Prevalence (Prevalência)</strong>: Proporção de instâncias reais de cada classe no conjunto de dados.
<ul>
<li><strong>CR</strong> tem a maior prevalência (55,31%).</li>
</ul></li>
<li><strong>Balanced Accuracy (Acurácia Balanceada)</strong>: Média da sensibilidade e especificidade para uma classe, útil para dados desbalanceados.
<ul>
<li>Alta para todas as classes, exceto CR, onde é moderada (0.8107).</li>
</ul></li>
</ul>
</section>
<section id="conclusão-4" class="level3" data-number="6.3">
<h3 data-number="6.3" class="anchored" data-anchor-id="conclusão-4"><span class="header-section-number">6.3</span> Conclusão</h3>
<p>O modelo apresenta boa acurácia geral (77,07%) e valores altos de sensibilidade e especificidade para a maioria das classes, exceto CR, que tem uma sensibilidade mais baixa (62,19%). A classe VEG tem um valor preditivo positivo muito baixo (13,57%), indicando que o modelo muitas vezes prevê incorretamente outras classes como VEG. A acurácia balanceada é alta para todas as classes, sugerindo que o modelo tem bom desempenho geral, apesar de algumas áreas para melhoria, especialmente na previsão correta da classe VEG e CR.</p>
<p><strong>Com este valor de acurácia (77,07%), considera-se que o modelo apresentou um resultado provável de ocorrer (<a href="#tbl-prob-result" class="quarto-xref">Tabela&nbsp;7</a>).</strong></p>
</section>
</section>
<section id="observações" class="level2" data-number="7">
<h2 data-number="7" class="anchored" data-anchor-id="observações"><span class="header-section-number">7</span> Observações</h2>
<ul>
<li><p>Recomenda se o uso com cautela deste dados estatístico.</p></li>
<li><p>As imagens usadas para a determinação das classes de validação possuem pixel nominal 5x5 metros mosaicos de imagens planet e a classificação original foi gerada com imagens com pixel &gt;= 30X30 metros</p></li>
<li><p>Para cálculos de biomassa área deve se redesenhar regionalmente os polígonos da classificação original para ter maior precisão nas estimativas</p></li>
<li><p>É muito importante ter as datas da detecção das classes originais dos polígonos principalmente para CSD, CSG E CQF, Pois estes processos são dinâmicos e num mesmo ano a classe pode passar de ‘VEG’, PARA ‘CSD’ E DEPOIS ‘CR’, E isso foi verificado neste processo de validação</p></li>
</ul>
</section>
<section id="referências" class="level2" data-number="8">
<h2 data-number="8" class="anchored" data-anchor-id="referências"><span class="header-section-number">8</span> Referências</h2>
<p>Adami, M.; Mello, M. P.; Aguiar, D. A.; Rudorff, B. F. T.; Souza, A. F. de. A Web platform development to perform thematic accuracy assessment of sugarcane mapping in South-Central Brazil. Remote Sensing, v. 4, n.10, p.&nbsp;3201-3214, 2012.</p>
<p>Olofsson, P., Foody, G. M., Herold, M., Stehman, S. V., Woodcock, C. E., &amp; Wulder, M. A. (2014). Good practices for estimating area and assessing accuracy of land change. Remote Sensing of Environment, 148, 42–57.</p>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copiada");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copiada");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<script>var lightboxQuarto = GLightbox({"closeEffect":"zoom","openEffect":"zoom","loop":false,"descPosition":"bottom","selector":".lightbox"});
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>