<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.5.57">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="ECODATAGEO">

<title>Accuracy analysis of deforestation and degradation activity data</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { display: inline-block; text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="relatorioIPAM_en_files/libs/clipboard/clipboard.min.js"></script>
<script src="relatorioIPAM_en_files/libs/quarto-html/quarto.js"></script>
<script src="relatorioIPAM_en_files/libs/quarto-html/popper.min.js"></script>
<script src="relatorioIPAM_en_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="relatorioIPAM_en_files/libs/quarto-html/anchor.min.js"></script>
<link href="relatorioIPAM_en_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="relatorioIPAM_en_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="relatorioIPAM_en_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="relatorioIPAM_en_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="relatorioIPAM_en_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script src="relatorioIPAM_en_files/libs/quarto-contrib/glightbox/glightbox.min.js"></script>
<link href="relatorioIPAM_en_files/libs/quarto-contrib/glightbox/glightbox.min.css" rel="stylesheet">
<link href="relatorioIPAM_en_files/libs/quarto-contrib/glightbox/lightbox.css" rel="stylesheet">

  <script src="https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

</head>

<body>

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a></li>
  <li><a href="#materials-and-methods" id="toc-materials-and-methods" class="nav-link" data-scroll-target="#materials-and-methods"><span class="header-section-number">2</span> Materials and Methods</a></li>
  <li><a href="#basic-statistics-by-classes" id="toc-basic-statistics-by-classes" class="nav-link" data-scroll-target="#basic-statistics-by-classes"><span class="header-section-number">3</span> Basic Statistics by classes</a>
  <ul class="collapse">
  <li><a href="#shallow-cut-cr" id="toc-shallow-cut-cr" class="nav-link" data-scroll-target="#shallow-cut-cr"><span class="header-section-number">3.1</span> Shallow Cut (CR)</a></li>
  <li><a href="#burn-scar-cqf" id="toc-burn-scar-cqf" class="nav-link" data-scroll-target="#burn-scar-cqf"><span class="header-section-number">3.2</span> Burn Scar (CQF)</a></li>
  <li><a href="#selective-cutting-sc" id="toc-selective-cutting-sc" class="nav-link" data-scroll-target="#selective-cutting-sc"><span class="header-section-number">3.3</span> Selective Cutting (SC)</a>
  <ul class="collapse">
  <li><a href="#cs-disordered" id="toc-cs-disordered" class="nav-link" data-scroll-target="#cs-disordered"><span class="header-section-number">3.3.1</span> CS Disordered</a></li>
  <li><a href="#cs-geometric" id="toc-cs-geometric" class="nav-link" data-scroll-target="#cs-geometric"><span class="header-section-number">3.3.2</span> CS Geometric</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#validation-procedures" id="toc-validation-procedures" class="nav-link" data-scroll-target="#validation-procedures"><span class="header-section-number">4</span> Validation Procedures</a></li>
  <li><a href="#accuracy-by-class" id="toc-accuracy-by-class" class="nav-link" data-scroll-target="#accuracy-by-class"><span class="header-section-number">5</span> Accuracy By Class</a>
  <ul class="collapse">
  <li><a href="#clear-cut-deforestation-cr" id="toc-clear-cut-deforestation-cr" class="nav-link" data-scroll-target="#clear-cut-deforestation-cr"><span class="header-section-number">5.1</span> Clear Cut Deforestation (CR)</a>
  <ul class="collapse">
  <li><a href="#interpretation" id="toc-interpretation" class="nav-link" data-scroll-target="#interpretation"><span class="header-section-number">5.1.1</span> Interpretation</a></li>
  <li><a href="#evaluation-metrics" id="toc-evaluation-metrics" class="nav-link" data-scroll-target="#evaluation-metrics"><span class="header-section-number">5.1.2</span> Evaluation Metrics</a></li>
  <li><a href="#sensitivity-and-specificity-metrics" id="toc-sensitivity-and-specificity-metrics" class="nav-link" data-scroll-target="#sensitivity-and-specificity-metrics"><span class="header-section-number">5.1.3</span> Sensitivity and Specificity Metrics</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">5.1.4</span> Conclusion</a></li>
  </ul></li>
  <li><a href="#burn-scar-cqf-1" id="toc-burn-scar-cqf-1" class="nav-link" data-scroll-target="#burn-scar-cqf-1"><span class="header-section-number">5.2</span> Burn Scar (CQF)</a>
  <ul class="collapse">
  <li><a href="#interpretation-1" id="toc-interpretation-1" class="nav-link" data-scroll-target="#interpretation-1"><span class="header-section-number">5.2.1</span> Interpretation</a></li>
  <li><a href="#evaluation-metrics-1" id="toc-evaluation-metrics-1" class="nav-link" data-scroll-target="#evaluation-metrics-1"><span class="header-section-number">5.2.2</span> Evaluation Metrics</a></li>
  <li><a href="#sensitivity-and-specificity-metrics-1" id="toc-sensitivity-and-specificity-metrics-1" class="nav-link" data-scroll-target="#sensitivity-and-specificity-metrics-1"><span class="header-section-number">5.2.3</span> Sensitivity and Specificity Metrics</a></li>
  <li><a href="#conclusion-1" id="toc-conclusion-1" class="nav-link" data-scroll-target="#conclusion-1"><span class="header-section-number">5.2.4</span> Conclusion</a></li>
  </ul></li>
  <li><a href="#disorderly-selective-logging-csd" id="toc-disorderly-selective-logging-csd" class="nav-link" data-scroll-target="#disorderly-selective-logging-csd"><span class="header-section-number">5.3</span> Disorderly Selective Logging (CSD)</a>
  <ul class="collapse">
  <li><a href="#interpretation-2" id="toc-interpretation-2" class="nav-link" data-scroll-target="#interpretation-2"><span class="header-section-number">5.3.1</span> Interpretation</a></li>
  <li><a href="#evaluation-metrics-2" id="toc-evaluation-metrics-2" class="nav-link" data-scroll-target="#evaluation-metrics-2"><span class="header-section-number">5.3.2</span> Evaluation Metrics</a></li>
  <li><a href="#sensitivity-and-specificity-metrics-2" id="toc-sensitivity-and-specificity-metrics-2" class="nav-link" data-scroll-target="#sensitivity-and-specificity-metrics-2"><span class="header-section-number">5.3.3</span> Sensitivity and Specificity Metrics</a></li>
  <li><a href="#conclusion-2" id="toc-conclusion-2" class="nav-link" data-scroll-target="#conclusion-2"><span class="header-section-number">5.3.4</span> Conclusion</a></li>
  </ul></li>
  <li><a href="#geometric-selective-logging-csg" id="toc-geometric-selective-logging-csg" class="nav-link" data-scroll-target="#geometric-selective-logging-csg"><span class="header-section-number">5.4</span> Geometric Selective Logging (CSG)</a>
  <ul class="collapse">
  <li><a href="#interpretation-3" id="toc-interpretation-3" class="nav-link" data-scroll-target="#interpretation-3"><span class="header-section-number">5.4.1</span> Interpretation</a></li>
  <li><a href="#evaluation-metrics-3" id="toc-evaluation-metrics-3" class="nav-link" data-scroll-target="#evaluation-metrics-3"><span class="header-section-number">5.4.2</span> Evaluation Metrics</a></li>
  <li><a href="#sensitivity-and-specificity-metrics-3" id="toc-sensitivity-and-specificity-metrics-3" class="nav-link" data-scroll-target="#sensitivity-and-specificity-metrics-3"><span class="header-section-number">5.4.3</span> Sensitivity and Specificity Metrics</a></li>
  <li><a href="#conclusion-3" id="toc-conclusion-3" class="nav-link" data-scroll-target="#conclusion-3"><span class="header-section-number">5.4.4</span> Conclusion</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#global-accuracy" id="toc-global-accuracy" class="nav-link" data-scroll-target="#global-accuracy"><span class="header-section-number">6</span> Global Accuracy</a>
  <ul class="collapse">
  <li><a href="#confusion-matrix-interpretation" id="toc-confusion-matrix-interpretation" class="nav-link" data-scroll-target="#confusion-matrix-interpretation"><span class="header-section-number">6.1</span> Confusion Matrix Interpretation</a></li>
  <li><a href="#evaluation-metrics-4" id="toc-evaluation-metrics-4" class="nav-link" data-scroll-target="#evaluation-metrics-4"><span class="header-section-number">6.2</span> Evaluation Metrics</a></li>
  <li><a href="#sensitivity-and-specificity-metrics-4" id="toc-sensitivity-and-specificity-metrics-4" class="nav-link" data-scroll-target="#sensitivity-and-specificity-metrics-4"><span class="header-section-number">6.3</span> Sensitivity and Specificity Metrics</a></li>
  <li><a href="#conclusion-4" id="toc-conclusion-4" class="nav-link" data-scroll-target="#conclusion-4"><span class="header-section-number">6.4</span> Conclusion</a></li>
  </ul></li>
  <li><a href="#uncertainty-calculation" id="toc-uncertainty-calculation" class="nav-link" data-scroll-target="#uncertainty-calculation"><span class="header-section-number">7</span> Uncertainty Calculation</a>
  <ul class="collapse">
  <li><a href="#mapping-uncertainties" id="toc-mapping-uncertainties" class="nav-link" data-scroll-target="#mapping-uncertainties"><span class="header-section-number">7.1</span> Mapping Uncertainties</a></li>
  <li><a href="#monte-carlo-uncertainty-calculation" id="toc-monte-carlo-uncertainty-calculation" class="nav-link" data-scroll-target="#monte-carlo-uncertainty-calculation"><span class="header-section-number">7.2</span> Monte Carlo Uncertainty Calculation</a></li>
  <li><a href="#procedures-for-monte-carlo-simulation-in-r" id="toc-procedures-for-monte-carlo-simulation-in-r" class="nav-link" data-scroll-target="#procedures-for-monte-carlo-simulation-in-r"><span class="header-section-number">7.3</span> Procedures for Monte Carlo Simulation in <em>R</em></a></li>
  <li><a href="#arttrees-spreadsheet" id="toc-arttrees-spreadsheet" class="nav-link" data-scroll-target="#arttrees-spreadsheet"><span class="header-section-number">7.4</span> <em>ART/TREES</em> Spreadsheet</a>
  <ul class="collapse">
  <li><a href="#key-data-needed-to-populate-the-spreadsheet" id="toc-key-data-needed-to-populate-the-spreadsheet" class="nav-link" data-scroll-target="#key-data-needed-to-populate-the-spreadsheet"><span class="header-section-number">7.4.1</span> Key Data Needed to Populate the Spreadsheet</a></li>
  <li><a href="#summary-of-tables-and-fields" id="toc-summary-of-tables-and-fields" class="nav-link" data-scroll-target="#summary-of-tables-and-fields"><span class="header-section-number">7.4.2</span> Summary of Tables and Fields</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">8</span> References</a></li>
  </ul>
<div class="quarto-alternate-formats"><h2>Other Formats</h2><ul><li><a href="relatorioIPAM_en.pdf"><i class="bi bi-file-pdf"></i>PDF</a></li><li><a href="relatorioIPAM_en.docx"><i class="bi bi-file-word"></i>MS Word</a></li></ul></div></nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Accuracy analysis of deforestation and degradation activity data</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>ECODATAGEO </p>
          </div>
  </div>
    
  
    
  </div>
  


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>There are a number of increasingly reliable, coherent and robust procedures for mapping and analyzing the dynamics of land use and occupation to satisfy a range of information needs for socio-environmental planning. These mappings, at a regional level, are carried out using remotely sensed images, which currently allow for daily analysis and high spatial resolution, making it essential to use robust and transparent statistical approaches to assess accuracy and estimate the area of change to ensure the integrity of information on land use changes (Olofsson et al.&nbsp;2014).</p>
<p>Accuracy analysis between mappings from different sources is the most common methodology for estimating hit and miss rates in thematic products derived from remote sensing. This approach involves comparing a mapped element with an ideal mapping result. To do this, a percentage of the mapping (samples) are selected to be validated and compared with the ideal mapping to calculate accuracy. The number and distribution of samples were generated according to the recommendations described in the works by Adami et al.&nbsp;2012 and Olofsson et al.&nbsp;2014.</p>
<p>In this analysis, we calculated, for the years 2017 to 2023 in the state of Pará, the accuracy of the mapping and the minimum number of sample points needed per mapping class: clear-cut deforestation (CR) and forest degradation, subdivided into: disorganized selective logging (CSD), geometric selective logging (CSG) and forest burn scar (CQF), in relation to the (ideal) reference mapping made by experts in photointerpretation of high spatial resolution images.</p>
</section>
<section id="materials-and-methods" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Materials and Methods</h1>
<p>As stipulated in the TR, IPAM shared data classified as ‘0’ and ‘1’ for deforestation and degradation activities in raster and vector format. The vectors (21 <em>shapefiles</em> in total) are derived from the raster data, as it was generated by the raster vectorization operation. The vector data that was used in the validation process is listed below:</p>
<div class="cell">
<div class="cell-output cell-output-stdout">
<pre><code> [1] "deter_fire_shp_2017.shp"           "deter_fire_shp_2018.shp"          
 [3] "deter_fire_shp_2019.shp"           "deter_fire_shp_2020.shp"          
 [5] "deter_fire_shp_2021.shp"           "deter_fire_shp_2022.shp"          
 [7] "deter_fire_shp_2023.shp"           "deter_logging_shp_2017.shp"       
 [9] "deter_logging_shp_2018.shp"        "deter_logging_shp_2019.shp"       
[11] "deter_logging_shp_2020.shp"        "deter_logging_shp_2021.shp"       
[13] "deter_logging_shp_2022.shp"        "deter_logging_shp_2023.shp"       
[15] "prodes_deforestation_shp_2017.shp" "prodes_deforestation_shp_2018.shp"
[17] "prodes_deforestation_shp_2019.shp" "prodes_deforestation_shp_2020.shp"
[19] "prodes_deforestation_shp_2021.shp" "prodes_deforestation_shp_2022.shp"
[21] "prodes_deforestation_shp_2023.shp"</code></pre>
</div>
</div>
<p>Com base nestes arquivos as classes de atividades consideradas foram:</p>
<div id="tbl-classes-atividades" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-classes-atividades-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Activity classes
</figcaption>
<div aria-describedby="tbl-classes-atividades-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 29%">
<col style="width: 18%">
<col style="width: 51%">
</colgroup>
<thead>
<tr class="header">
<th>Contractor Files</th>
<th>Class</th>
<th>Equivalent to</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>deter_fire…</td>
<td>Fire</td>
<td>Forest – Burned Area Scar in Forest (CQF)</td>
</tr>
<tr class="even">
<td>deter_logging…</td>
<td>Logging</td>
<td>Forest – Selective logging (CSD-1) or geometric (CSG-2)</td>
</tr>
<tr class="odd">
<td>prodes_deforestation…</td>
<td>Deforestation</td>
<td>Forest – Clear-cutting (CR)</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>In all the vectors, their attribute tables contained only two fields: “count”, which represents the number of pixels in the polygon’s geometry; and “label”, a numeric field where ‘1’ represents the mapping class to be validated (CR, CSD, CSG or CQF) and ‘0’ represents the other classes combined as one (mainly native vegetation and water bodies). For logging data only, the label is numbered “1” for CSD and “2” for CSG.</p>
<p>All the <em>shapefiles</em> had their geometry converted to “<em>Singlepolygon</em>”, which individualizes the feature with more than one associated geometry, leaving the feature associated with only one geometry. After this operation, the areas of the polygons were recalculated in the QGIS software, in the field calculator, with the “<em>$area</em>” function. We generated the centroids (geographical coordinates of the center) of all the deforestation and degradation polygons, which facilitates the GIS operations for the statistical calculations, in ‘R’ language, of the minimum number of samples per class per year to be validated. The <a href="#tbl-pols-area" class="quarto-xref">Table&nbsp;2</a> displays the result of these operations.</p>
<div id="tbl-pols-area" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-pols-area-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Number of polygons and total area of activity classes per year, provided by IPAM
</figcaption>
<div aria-describedby="tbl-pols-area-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<thead>
<tr class="header">
<th>Class</th>
<th>Nº Polygons</th>
<th>Area (ha)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>deforestation_2017</td>
<td>34,730</td>
<td>296,009</td>
</tr>
<tr class="even">
<td>deforestation_2018</td>
<td>36,031</td>
<td>295,513</td>
</tr>
<tr class="odd">
<td>deforestation_2019</td>
<td>38,084</td>
<td>484,068</td>
</tr>
<tr class="even">
<td>deforestation_2020</td>
<td>41,327</td>
<td>504,779</td>
</tr>
<tr class="odd">
<td>deforestation_2021</td>
<td>45,674</td>
<td>560,919</td>
</tr>
<tr class="even">
<td>deforestation_2022</td>
<td>34,544</td>
<td>492,304</td>
</tr>
<tr class="odd">
<td>deforestation_2023</td>
<td>33,883</td>
<td>333,670</td>
</tr>
<tr class="even">
<td>fire_2017</td>
<td>2,121</td>
<td>438,550</td>
</tr>
<tr class="odd">
<td>fire_2018</td>
<td>3,656</td>
<td>891,603</td>
</tr>
<tr class="even">
<td>fire_2019</td>
<td>324</td>
<td>14,903.9</td>
</tr>
<tr class="odd">
<td>fire_2020</td>
<td>2,163</td>
<td>211,999</td>
</tr>
<tr class="even">
<td>fire_2021</td>
<td>2,748</td>
<td>393,183</td>
</tr>
<tr class="odd">
<td>fire_2022</td>
<td>643</td>
<td>45,482.7</td>
</tr>
<tr class="even">
<td>fire_2023</td>
<td>2,344</td>
<td>350,464</td>
</tr>
<tr class="odd">
<td>logging_2017</td>
<td>97</td>
<td>40,717.6</td>
</tr>
<tr class="even">
<td>logging_2018</td>
<td>71</td>
<td>42,030.9</td>
</tr>
<tr class="odd">
<td>logging_2019</td>
<td>62</td>
<td>28,901.2</td>
</tr>
<tr class="even">
<td>logging_2020</td>
<td>237</td>
<td>111,370</td>
</tr>
<tr class="odd">
<td>logging_2021</td>
<td>364</td>
<td>118,286</td>
</tr>
<tr class="even">
<td>logging_2022</td>
<td>277</td>
<td>114,618</td>
</tr>
<tr class="odd">
<td>logging_2023</td>
<td>194</td>
<td>98,258.9</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>The accuracy metrics followed what is required by the ART/TREES standard <a href="#fn1" class="footnote-ref" id="fnref1" role="doc-noteref"><sup>1</sup></a>, guided by the recommendations of the works by Adami et al.&nbsp;2012 and Olofsson et al.&nbsp;2014, the stratified sampling method was adopted to determine the number of validation samples for each class per year, this method being consistent with calculating the proportion of each stratum in relation to the total population and obtaining an ideal number of samples. The minimum number of samples (n) per class for validation was calculated by applying <a href="#eq-adami" class="quarto-xref">Equation&nbsp;1</a>.</p>
<p><span id="eq-adami"><span class="math display">\[
n = \frac{(Z\alpha/2)^2 \times p \times q}{e^2}
\tag{1}\]</span></span></p>
<p>Where:</p>
<p><span class="math inline">\(n\)</span> = sample size</p>
<p><span class="math inline">\(Z(\alpha/2)\)</span> = critical value corresponding to the degree of confidence (95%)</p>
<p><span class="math inline">\(p\)</span> = population proportion of individuals belonging to a given category</p>
<p><span class="math inline">\(q\)</span> = population proportion of individuals not belonging to a given category (1 - p)</p>
<p><span class="math inline">\(e\)</span> = margin of error (2.5%)</p>
<p>Or as defined by Olofsson et al.&nbsp;2014:</p>
<p><span id="eq-olofsson"><span class="math display">\[
n = (\frac{\Sigma W_{i}S_{i}}{S(\tilde{O})})^2
\tag{2}\]</span></span></p>
<p>Where, n = sample size,</p>
<p><span class="math inline">\(W_{i}\)</span> area of class <em>i</em>,</p>
<p><span class="math inline">\(S_{i}\)</span> is the standard deviation of stratum <em>i</em>, <span class="math inline">\(S_{i} = \sqrt{U{i}(1 - U_{i})}\)</span></p>
<p><span class="math inline">\(S(\tilde{O})\)</span> is the standard error</p>
<p>Thus, the number of sample points for each disturbance category was defined as <a href="#tbl-points-year" class="quarto-xref">Table&nbsp;3</a> for all years, <a href="#tbl-points-2017" class="quarto-xref">Table&nbsp;4</a> for the year 2017, <a href="#tbl-points-2018" class="quarto-xref">Table&nbsp;5</a> for 2018, <a href="#tbl-points-2019" class="quarto-xref">Table&nbsp;6</a> for 2019, <a href="#tbl-points-2020" class="quarto-xref">Table&nbsp;7</a> for 2020, <a href="#tbl-points-2021" class="quarto-xref">Table&nbsp;8</a> for 2021, <a href="#tbl-points-2022" class="quarto-xref">Table&nbsp;9</a> for 2022 and <a href="#tbl-points-2023" class="quarto-xref">Table&nbsp;10</a> for 2023.</p>
<div id="tbl-points-year" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-points-year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;3: Result of applying equation (1) considering the data from all the years together.
</figcaption>
<div aria-describedby="tbl-points-year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 14%">
<col style="width: 14%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 26%">
<col style="width: 30%">
</colgroup>
<thead>
<tr class="header">
<th>Class</th>
<th>Nº Polygons</th>
<th>p</th>
<th>q</th>
<th>Average Sample No.&nbsp;/ Year</th>
<th>Sample No.&nbsp;Total Calculated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Deforestation</td>
<td>264,273</td>
<td>0.946</td>
<td>0.054</td>
<td>314.08</td>
<td>2198.53</td>
</tr>
<tr class="even">
<td>Fire</td>
<td>13,999</td>
<td>0.049</td>
<td>0.951</td>
<td>288.85</td>
<td>2021.96</td>
</tr>
<tr class="odd">
<td>CSD - 1</td>
<td>792</td>
<td>0.003</td>
<td>0.997</td>
<td>17.60</td>
<td>123.21</td>
</tr>
<tr class="even">
<td>CSG - 2</td>
<td>510</td>
<td>0.002</td>
<td>0.998</td>
<td>10.47</td>
<td>73.26</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-points-2017" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-points-2017-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;4: Result of applying equation (1) for the year 2017.
</figcaption>
<div aria-describedby="tbl-points-2017-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 26%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Class - 2017</th>
<th>Nº Polygons</th>
<th>p</th>
<th>q</th>
<th>Average Sample No.&nbsp;/ Year</th>
<th>Sample No.&nbsp;Total Calculated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Deforestation</td>
<td>34,730</td>
<td>0.940</td>
<td>0.060</td>
<td>346.830</td>
<td>347</td>
</tr>
<tr class="even">
<td>Fire</td>
<td>2,121</td>
<td>0.057</td>
<td>0.943</td>
<td>332.588</td>
<td>332</td>
</tr>
<tr class="odd">
<td>CSD - 1</td>
<td>56</td>
<td>0.002</td>
<td>0.998</td>
<td>9.302</td>
<td>10</td>
</tr>
<tr class="even">
<td>CSG - 2</td>
<td>41</td>
<td>0.001</td>
<td>0.999</td>
<td>6.813</td>
<td>7</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-points-2018" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-points-2018-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;5: Result of applying equation (1) for the year 2018.
</figcaption>
<div aria-describedby="tbl-points-2018-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 26%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Class - 2018</th>
<th>Nº Polygons</th>
<th>p</th>
<th>q</th>
<th>Average Sample No.&nbsp;/ Year</th>
<th>Sample No.&nbsp;Total Calculated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Deforestation</td>
<td>36,031</td>
<td>0.906</td>
<td>0.094</td>
<td>522.178</td>
<td>523</td>
</tr>
<tr class="even">
<td>Fire</td>
<td>3,656</td>
<td>0.092</td>
<td>0.908</td>
<td>513.240</td>
<td>514</td>
</tr>
<tr class="odd">
<td>CSD - 1</td>
<td>47</td>
<td>0.001</td>
<td>0.999</td>
<td>7.258</td>
<td>8</td>
</tr>
<tr class="even">
<td>CSG - 2</td>
<td>24</td>
<td>0.001</td>
<td>0.999</td>
<td>3.708</td>
<td>4</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-points-2019" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-points-2019-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;6: Result of applying equation (1) for the year 2019.
</figcaption>
<div aria-describedby="tbl-points-2019-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 26%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Class - 2019</th>
<th>Nº Polygons</th>
<th>p</th>
<th>q</th>
<th>Average Sample No.&nbsp;/ Year</th>
<th>Sample No.&nbsp;Total Calculated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Deforestation</td>
<td>38,084</td>
<td>0.990</td>
<td>0.010</td>
<td>61.054</td>
<td>62</td>
</tr>
<tr class="even">
<td>Fire</td>
<td>324</td>
<td>0.008</td>
<td>0.992</td>
<td>51.331</td>
<td>52</td>
</tr>
<tr class="odd">
<td>CSD - 1</td>
<td>31</td>
<td>0.001</td>
<td>0.999</td>
<td>4.949</td>
<td>5</td>
</tr>
<tr class="even">
<td>CSG - 2</td>
<td>31</td>
<td>0.001</td>
<td>0.999</td>
<td>4.949</td>
<td>5</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-points-2020" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-points-2020-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;7: Result of applying equation (1) for the year 2020.
</figcaption>
<div aria-describedby="tbl-points-2020-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 26%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Class - 2020</th>
<th>Nº Polygons</th>
<th>p</th>
<th>q</th>
<th>Average Sample No.&nbsp;/ Year</th>
<th>Sample No.&nbsp;Total Calculated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Deforestation</td>
<td>41,327</td>
<td>0.945</td>
<td>0.055</td>
<td>318.844</td>
<td>318</td>
</tr>
<tr class="even">
<td>Fire</td>
<td>2,163</td>
<td>0.049</td>
<td>0.951</td>
<td>289.006</td>
<td>289</td>
</tr>
<tr class="odd">
<td>CSD - 1</td>
<td>191</td>
<td>0.004</td>
<td>0.996</td>
<td>26.731</td>
<td>27</td>
</tr>
<tr class="even">
<td>CSG - 2</td>
<td>46</td>
<td>0.001</td>
<td>0.999</td>
<td>6.459</td>
<td>7</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-points-2021" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-points-2021-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;8: Result of applying equation (1) for the year 2021.
</figcaption>
<div aria-describedby="tbl-points-2021-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 26%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Class - 2021</th>
<th>Nº Polygons</th>
<th>p</th>
<th>q</th>
<th>Average Sample No.&nbsp;/ Year</th>
<th>Sample No.&nbsp;Total Calculated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Deforestation</td>
<td>45,674</td>
<td>0.936</td>
<td>0.064</td>
<td>367.071</td>
<td>365</td>
</tr>
<tr class="even">
<td>Fire</td>
<td>2,748</td>
<td>0.056</td>
<td>0.944</td>
<td>326.719</td>
<td>327</td>
</tr>
<tr class="odd">
<td>CSD - 1</td>
<td>108</td>
<td>0.002</td>
<td>0.998</td>
<td>13.577</td>
<td>14</td>
</tr>
<tr class="even">
<td>CSG - 2</td>
<td>256</td>
<td>0.005</td>
<td>0.995</td>
<td>32.084</td>
<td>33</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-points-2022" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-points-2022-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;9: Result of applying equation (1) for the year 2022.
</figcaption>
<div aria-describedby="tbl-points-2022-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 26%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Class - 2022</th>
<th>Nº Polygons</th>
<th>p</th>
<th>q</th>
<th>Average Sample No.&nbsp;/ Year</th>
<th>Sample No.&nbsp;Total Calculated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Deforestation</td>
<td>34,544</td>
<td>0.974</td>
<td>0.026</td>
<td>155.316</td>
<td>152</td>
</tr>
<tr class="even">
<td>Fire</td>
<td>643</td>
<td>0.018</td>
<td>0.982</td>
<td>109.423</td>
<td>110</td>
</tr>
<tr class="odd">
<td>CSD - 1</td>
<td>216</td>
<td>0.006</td>
<td>0.994</td>
<td>37.209</td>
<td>38</td>
</tr>
<tr class="even">
<td>CSG - 2</td>
<td>61</td>
<td>0.002</td>
<td>0.998</td>
<td>10.554</td>
<td>11</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<div id="tbl-points-2023" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-points-2023-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;10: Result of applying equation (1) for the year 2023.
</figcaption>
<div aria-describedby="tbl-points-2023-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 17%">
<col style="width: 15%">
<col style="width: 7%">
<col style="width: 7%">
<col style="width: 26%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th>Class - 2023</th>
<th>Nº Polygons</th>
<th>p</th>
<th>q</th>
<th>Average Sample No.&nbsp;/ Year</th>
<th>Sample No.&nbsp;Total Calculated</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Deforestation</td>
<td>33,883</td>
<td>0.930</td>
<td>0.070</td>
<td>398.476</td>
<td>398</td>
</tr>
<tr class="even">
<td>Fire</td>
<td>2,344</td>
<td>0.064</td>
<td>0.936</td>
<td>370.124</td>
<td>130</td>
</tr>
<tr class="odd">
<td>CSD - 1</td>
<td>143</td>
<td>0.004</td>
<td>0.996</td>
<td>24.039</td>
<td>25</td>
</tr>
<tr class="even">
<td>CSG - 2</td>
<td>51</td>
<td>0.001</td>
<td>0.999</td>
<td>8.595</td>
<td>9</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="basic-statistics-by-classes" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Basic Statistics by classes</h1>
<div id="tbl-classes-year" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-classes-year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;11: Number and percentage of polygons per class/year. <em>clas_valid</em> = class defined by the analyst according to <a href="#tbl-classes" class="quarto-xref">Table&nbsp;16</a>. pol = polygons.
</figcaption>
<div aria-describedby="tbl-classes-year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<thead>
<tr class="header">
<th>class_valid</th>
<th>nº pol 2017</th>
<th>% 2017</th>
<th>nº pol 2018</th>
<th>% 2018</th>
<th>nº pol 2019</th>
<th>% 2019</th>
<th>nº pol 2020</th>
<th>% 2020</th>
<th>nº pol 2021</th>
<th>% 2021</th>
<th>nº pol 2022</th>
<th>% 2022</th>
<th>nº pol 2023</th>
<th>% 2023</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1-true</td>
<td>237</td>
<td>0,683</td>
<td>330</td>
<td>0,631</td>
<td>44</td>
<td>0,71</td>
<td>194</td>
<td>0,61</td>
<td>270</td>
<td>0,74</td>
<td>104</td>
<td>0,684</td>
<td>239</td>
<td>0,601</td>
</tr>
<tr class="even">
<td>1-false</td>
<td>102</td>
<td>0,294</td>
<td>182</td>
<td>0,348</td>
<td>16</td>
<td>0,258</td>
<td>94</td>
<td>0,296</td>
<td>70</td>
<td>0,192</td>
<td>36</td>
<td>0,237</td>
<td>139</td>
<td>0,349</td>
</tr>
<tr class="odd">
<td>0-veg</td>
<td>8</td>
<td>0,023</td>
<td>10</td>
<td>0,019</td>
<td>2</td>
<td>0,032</td>
<td>30</td>
<td>0,094</td>
<td>22</td>
<td>0,06</td>
<td>7</td>
<td>0,046</td>
<td>11</td>
<td>0,028</td>
</tr>
<tr class="even">
<td>2-cs</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0,002</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>3</td>
<td>0,008</td>
<td>5</td>
<td>0,033</td>
<td>9</td>
<td>0,023</td>
</tr>
<tr class="odd">
<td>3-cqf</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="even">
<td>4-others</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
</tr>
<tr class="odd">
<td>Total</td>
<td>347</td>
<td>1</td>
<td>523</td>
<td>1</td>
<td>62</td>
<td>1</td>
<td>318</td>
<td>1</td>
<td>365</td>
<td>1</td>
<td>152</td>
<td>1</td>
<td>398</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="shallow-cut-cr" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="shallow-cut-cr"><span class="header-section-number">3.1</span> Shallow Cut (CR)</h2>
<div id="tbl-cr-classes-year" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cr-classes-year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;12: Number and percentage of CR class polygons per year. <em>clas_valid</em> = class defined by the analyst according to <a href="#tbl-classes" class="quarto-xref">Table&nbsp;16</a>. pol = polygons.
</figcaption>
<div aria-describedby="tbl-cr-classes-year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>class_valid</th>
<th>1-true</th>
<th>1-false</th>
<th>0-veg</th>
<th>2-cs</th>
<th>3-cqf</th>
<th>4-others</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>nº pol 2017</td>
<td>237</td>
<td>102</td>
<td>8</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>347</td>
</tr>
<tr class="even">
<td>nº pol 2018</td>
<td>330</td>
<td>182</td>
<td>10</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>523</td>
</tr>
<tr class="odd">
<td>nº pol 2019</td>
<td>44</td>
<td>16</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>62</td>
</tr>
<tr class="even">
<td>nº pol 2020</td>
<td>194</td>
<td>94</td>
<td>30</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>318</td>
</tr>
<tr class="odd">
<td>nº pol 2021</td>
<td>270</td>
<td>70</td>
<td>22</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>365</td>
</tr>
<tr class="even">
<td>nº pol 2022</td>
<td>104</td>
<td>36</td>
<td>7</td>
<td>5</td>
<td>0</td>
<td>0</td>
<td>152</td>
</tr>
<tr class="odd">
<td>nº pol 2023</td>
<td>239</td>
<td>139</td>
<td>11</td>
<td>9</td>
<td>0</td>
<td>0</td>
<td>398</td>
</tr>
<tr class="even">
<td>TOTAL</td>
<td>1418</td>
<td>639</td>
<td>90</td>
<td>18</td>
<td>0</td>
<td>0</td>
<td>2165</td>
</tr>
<tr class="odd">
<td>% TOTAL</td>
<td>0,654</td>
<td>0,295</td>
<td>0,0415</td>
<td>0,008</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="burn-scar-cqf" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="burn-scar-cqf"><span class="header-section-number">3.2</span> Burn Scar (CQF)</h2>
<div id="tbl-cqf-classes-year" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-cqf-classes-year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;13: Number and percentage of CQF class polygons per year. <em>clas_valid</em> = class defined by the analyst according to <a href="#tbl-classes" class="quarto-xref">Table&nbsp;16</a>. pol = polygons.
</figcaption>
<div aria-describedby="tbl-cqf-classes-year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 8%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>class_valid</th>
<th>3-true</th>
<th>3-false</th>
<th>0-veg</th>
<th>2-cs</th>
<th>1-cr</th>
<th>4-others</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>nº pol 2017</td>
<td>241</td>
<td>31</td>
<td>33</td>
<td>12</td>
<td>14</td>
<td>1</td>
<td>332</td>
</tr>
<tr class="even">
<td>nº pol 2018</td>
<td>431</td>
<td>0</td>
<td>19</td>
<td>5</td>
<td>59</td>
<td>0</td>
<td>514</td>
</tr>
<tr class="odd">
<td>nº pol 2019</td>
<td>33</td>
<td>0</td>
<td>4</td>
<td>0</td>
<td>15</td>
<td>0</td>
<td>52</td>
</tr>
<tr class="even">
<td>nº pol 2020</td>
<td>231</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>55</td>
<td>3</td>
<td>289</td>
</tr>
<tr class="odd">
<td>nº pol 2021</td>
<td>292</td>
<td>0</td>
<td>2</td>
<td>0</td>
<td>31</td>
<td>2</td>
<td>327</td>
</tr>
<tr class="even">
<td>nº pol 2022</td>
<td>92</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>17</td>
<td>0</td>
<td>110</td>
</tr>
<tr class="odd">
<td>nº pol 2023</td>
<td>121</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>9</td>
<td>0</td>
<td>130</td>
</tr>
<tr class="even">
<td>TOTAL</td>
<td>1441</td>
<td>31</td>
<td>58</td>
<td>18</td>
<td>200</td>
<td>6</td>
<td>1754</td>
</tr>
<tr class="odd">
<td>% TOTAL</td>
<td>0,822</td>
<td>0,018</td>
<td>0,033</td>
<td>0,01</td>
<td>0,114</td>
<td>0,003</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="selective-cutting-sc" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="selective-cutting-sc"><span class="header-section-number">3.3</span> Selective Cutting (SC)</h2>
<section id="cs-disordered" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="cs-disordered"><span class="header-section-number">3.3.1</span> CS Disordered</h3>
<div id="tbl-csd-classes-year" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-csd-classes-year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;14: Number and percentage of CSD class polygons per year. <em>clas_valid</em> = class defined by the analyst according to <a href="#tbl-classes" class="quarto-xref">Table&nbsp;16</a>. pol = polygons.
</figcaption>
<div aria-describedby="tbl-csd-classes-year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 18%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 11%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>class_valid</th>
<th>2-true</th>
<th>2-false</th>
<th>0-veg</th>
<th>1-cr</th>
<th>3-cqf</th>
<th>4-others</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>nº pol 2017</td>
<td>6</td>
<td>3</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>10</td>
</tr>
<tr class="even">
<td>nº pol 2018</td>
<td>8</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>8</td>
</tr>
<tr class="odd">
<td>nº pol 2019</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>5</td>
</tr>
<tr class="even">
<td>nº pol 2020</td>
<td>21</td>
<td>5</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>27</td>
</tr>
<tr class="odd">
<td>nº pol 2021</td>
<td>270</td>
<td>70</td>
<td>22</td>
<td>3</td>
<td>0</td>
<td>0</td>
<td>365</td>
</tr>
<tr class="even">
<td>nº pol 2022</td>
<td>31</td>
<td>7</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>38</td>
</tr>
<tr class="odd">
<td>nº pol 2023</td>
<td>20</td>
<td>5</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>25</td>
</tr>
<tr class="even">
<td>TOTAL</td>
<td>360</td>
<td>90</td>
<td>24</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>478</td>
</tr>
<tr class="odd">
<td>% TOTAL</td>
<td>0,753</td>
<td>0,188</td>
<td>0,0502</td>
<td>0,008</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
<section id="cs-geometric" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="cs-geometric"><span class="header-section-number">3.3.2</span> CS Geometric</h3>
<div id="tbl-csg-classes-year" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-csg-classes-year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;15: Number and percentage of CSG class polygons per year. <em>clas_valid</em> = class defined by the analyst according to <a href="#tbl-classes" class="quarto-xref">Table&nbsp;16</a>. pol = polygons.
</figcaption>
<div aria-describedby="tbl-csg-classes-year-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 19%">
<col style="width: 11%">
<col style="width: 13%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 10%">
<col style="width: 14%">
<col style="width: 10%">
</colgroup>
<thead>
<tr class="header">
<th>class_valid</th>
<th>2-true</th>
<th>2-false</th>
<th>0-veg</th>
<th>1-cr</th>
<th>3-cqf</th>
<th>4-others</th>
<th>Total</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>nº pol 2017</td>
<td>7</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>7</td>
</tr>
<tr class="even">
<td>nº pol 2018</td>
<td>4</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>4</td>
</tr>
<tr class="odd">
<td>nº pol 2019</td>
<td>4</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>5</td>
</tr>
<tr class="even">
<td>nº pol 2020</td>
<td>6</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>7</td>
</tr>
<tr class="odd">
<td>nº pol 2021</td>
<td>31</td>
<td>0</td>
<td>0</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>33</td>
</tr>
<tr class="even">
<td>nº pol 2022</td>
<td>9</td>
<td>0</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>11</td>
</tr>
<tr class="odd">
<td>nº pol 2023</td>
<td>8</td>
<td>1</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>0</td>
<td>9</td>
</tr>
<tr class="even">
<td>TOTAL</td>
<td>69</td>
<td>3</td>
<td>2</td>
<td>2</td>
<td>0</td>
<td>0</td>
<td>76</td>
</tr>
<tr class="odd">
<td>% TOTAL</td>
<td>0,908</td>
<td>0,039</td>
<td>0,026</td>
<td>0,026</td>
<td>0</td>
<td>0</td>
<td>1</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
</section>
</section>
</section>
<section id="validation-procedures" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Validation Procedures</h1>
<p>To validate the activity classes, the analysts pre-defined five reference mapping classes, each associated with a numerical value according to <a href="#tbl-classes" class="quarto-xref">Table&nbsp;16</a>. This was done to make it easier to fill in the attribute table for the validation samples and then draw up the confusion matrices.</p>
<div id="tbl-classes" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-classes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;16: <strong>NUMERIC VALUE OF VALIDATION CLASSES</strong> (<em>clas_valid</em> column in the attribute tables of vector files. *WATER, SHADOW, CLOUDS, HERBACEOUS FLOODPLAIN, MEANDERS).
</figcaption>
<div aria-describedby="tbl-classes-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<thead>
<tr class="header">
<th style="text-align: right;">Class</th>
<th style="text-align: center;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: right;">FOREST/NATIVE VEG (VEG)</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: right;">CLEAR-CUT (CR)</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">SELECTIVE CUT-CS</td>
<td style="text-align: center;">2</td>
</tr>
<tr class="even">
<td style="text-align: right;">DISORDERLY CS (CSD)</td>
<td style="text-align: center;">2.1</td>
</tr>
<tr class="odd">
<td style="text-align: right;">GEOMETRIC CS (CSG)</td>
<td style="text-align: center;">2.2</td>
</tr>
<tr class="even">
<td style="text-align: right;">BURN SCAR IN FOREST (CQF)</td>
<td style="text-align: center;">3</td>
</tr>
<tr class="odd">
<td style="text-align: right;">*OTHERS</td>
<td style="text-align: center;">4</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<p>After the selection of sample points, presented in item 3, the polygons associated with each point were analyzed by the photointerpretation specialist, using monthly mosaics of high-resolution images from the Planet constellation as reference.</p>
<p>In the vector data of the samples selected for validation, two fields were created in the attribute table: <em>clas_valid</em> and <em>label</em>, as follows:</p>
<p><em>clas_valid</em> ➞ this attribute represents the class defined by the analyst according to <a href="#tbl-classes" class="quarto-xref">Table&nbsp;16</a></p>
<p><em>label</em> ➞ boolean data, where FALSE = 0, TRUE = 1. That is, <em>label</em> = 0 means WRONG ORIGINAL CLASS OF POLYGON (false positive), and <em>label</em> = 1 means TRUE POLYGON.</p>
<p>Examples of combinations:</p>
<p><em>label</em> = 0 and <em>clas_valid</em> = ANY VALUE FROM <a href="#tbl-classes" class="quarto-xref">Table&nbsp;16</a>, means NEGATIVE VALIDATION, ORIGINAL POLYGON = FALSE;</p>
<p><em>label</em> = 1 and <em>clas_valid</em> = ANY VALUE FROM <a href="#tbl-classes" class="quarto-xref">Table&nbsp;16</a>, means POSITIVE VALIDATION, ORIGINAL POLYGON = TRUE.</p>
<p>Since the original data comes from INPE’s mappings, the PRODES year was used as a reference period for the annual accuracy assessment of the mapped classes. The current year was considered as the period from August 1st of the previous year to July 31st of the current year. For example: deforestation for the year 2021 includes polygons detected between 08/01/2020 and 07/31/2021.</p>
<p>When conducting the validation, if the polygon selected for validation showed a mix of classes, the value of the <em>clas_valid</em> attribute that had the greatest area representation (&gt;=50%) was filled in.</p>
<p>The validation of the 2017 CQF class presented the combination <em>label</em> = 0 &amp; <em>clas_valid</em> = 3, where the burn scar was present before 08/01/2016, but was not identified in the current year’s photointerpretation, and therefore should be counted for the year 2016. See <a href="#fig-cqf-false" class="quarto-xref">Figure&nbsp;5</a> and <a href="#fig-cqf-true" class="quarto-xref">Figure&nbsp;6</a>.</p>
<p>In the validation of selective logging, the combination <em>label</em> = 0 &amp; <em>clas_valid</em> = 2 shows that there is selective logging, but the subclass was incorrect, either disorderly (2.1) or geometric (2.2). Additionally, it is difficult to separate the CSD from CSG classes (see <a href="#fig-cs-false" class="quarto-xref">Figure&nbsp;1</a> and <a href="#fig-cs-true" class="quarto-xref">Figure&nbsp;2</a>). It is possible to identify areas (e.g., in 2021) that show temporal variations in these classes, where in the same year, in month T0 the class was CSG, in T1 the class became CSD (indicating a likely period of intense logging activity, machinery movement), and in T3 it returned to CSG (only secondary exploitation areas being visible). For this reason, the detection date is important to be made available with the classified data.</p>
<p>In the analysis of clear-cutting, in the annual mapping averages, 84% of polygons considered false by the photo interpreter (<em>label</em> = 0 &amp; <em>clas_valid</em> = 1) are true deforestation features but were already present in the previous year. See <a href="#fig-cr-false" class="quarto-xref">Figure&nbsp;3</a> and <a href="#fig-cr-true" class="quarto-xref">Figure&nbsp;4</a>.</p>
<div id="fig-cs-false" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cs-false-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-false" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-veg-0-19" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-veg-0-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/0_veg_jul_2019.png" class="lightbox" data-gallery="fig-cs-false" title="Figure&nbsp;1&nbsp;(a): VEG = 0. July 2019"><img src="images/0_veg_jul_2019.png" class="img-fluid figure-img" data-ref-parent="fig-cs-false"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-veg-0-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) VEG = 0. July 2019
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-false" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-veg-0-20" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-veg-0-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/0_veg_jul_2020.png" class="lightbox" data-gallery="fig-cs-false" title="Figure&nbsp;1&nbsp;(b): VEG = 0. July 2020"><img src="images/0_veg_jul_2020.png" class="img-fluid figure-img" data-ref-parent="fig-cs-false"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-veg-0-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) VEG = 0. July 2020
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-false" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csd-csg-1-19" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csd-csg-1-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/1_csd_para_csg_set_2019.png" class="lightbox" data-gallery="fig-cs-false" title="Figure&nbsp;1&nbsp;(c): CSD = 1 to CSG. September 2019"><img src="images/1_csd_para_csg_set_2019.png" class="img-fluid figure-img" data-ref-parent="fig-cs-false"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csd-csg-1-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) CSD = 1 to CSG. September 2019
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-false" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csd-csg-2-20" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csd-csg-2-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/2_csd_para_csg_set_2020.png" class="lightbox" data-gallery="fig-cs-false" title="Figure&nbsp;1&nbsp;(d): CSD = 2 to CSG. September 2020"><img src="images/2_csd_para_csg_set_2020.png" class="img-fluid figure-img" data-ref-parent="fig-cs-false"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csd-csg-2-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) CSD = 2 to CSG. September 2020
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-false" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csg-csd-2-18" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csg-csd-2-18-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/2_csg_para_csd_out_2018.png" class="lightbox" data-gallery="fig-cs-false" title="Figure&nbsp;1&nbsp;(e): CSG = 2 to CSD. October 2019"><img src="images/2_csg_para_csd_out_2018.png" class="img-fluid figure-img" data-ref-parent="fig-cs-false"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csg-csd-2-18-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(e) CSG = 2 to CSD. October 2019
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cs-false-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Corte Seletivo (CS) FALSE
</figcaption>
</figure>
</div>
<div id="fig-cs-true" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cs-true-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-true" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csd-0-19" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csd-0-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/0_csd_ago_2019.png" class="lightbox" data-gallery="fig-cs-true" title="Figure&nbsp;2&nbsp;(a): CSD = 0. August 2019"><img src="images/0_csd_ago_2019.png" class="img-fluid figure-img" data-ref-parent="fig-cs-true"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csd-0-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(a) CSD = 0. August 2019
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="images/0_csd_jul_2020.png" class="img-fluid figure-img"></p>
<figcaption>CSD = 0. July 2020</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-true" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csg-1-19" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csg-1-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/1_csg_ago_2019.png" class="lightbox" data-gallery="fig-cs-true" title="Figure&nbsp;2&nbsp;(b): CSG = 1. August 2019"><img src="images/1_csg_ago_2019.png" class="img-fluid figure-img" data-ref-parent="fig-cs-true"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csg-1-19-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(b) CSG = 1. August 2019
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-true" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csg-1-20" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csg-1-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/1_csg_jul_2020.png" class="lightbox" data-gallery="fig-cs-true" title="Figure&nbsp;2&nbsp;(c): CSG = 1. July 2020"><img src="images/1_csg_jul_2020.png" class="img-fluid figure-img" data-ref-parent="fig-cs-true"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csg-1-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(c) CSG = 1. July 2020
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-true" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csg-2-17" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csg-2-17-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/2_csg_jul_2017.png" class="lightbox" data-gallery="fig-cs-true" title="Figure&nbsp;2&nbsp;(d): CSG = 2. July 2017"><img src="images/2_csg_jul_2017.png" class="img-fluid figure-img" data-ref-parent="fig-cs-true"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csg-2-17-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(d) CSG = 2. July 2017
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-true" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csg-2-18" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csg-2-18-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/2_csg_mar_2018.png" class="lightbox" data-gallery="fig-cs-true" title="Figure&nbsp;2&nbsp;(e): CSG = 2. March 2018"><img src="images/2_csg_mar_2018.png" class="img-fluid figure-img" data-ref-parent="fig-cs-true"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csg-2-18-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(e) CSG = 2. March 2018
</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-true" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csd-3-21" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csd-3-21-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/3_csd_abr_2021.png" class="lightbox" data-gallery="fig-cs-true" title="Figure&nbsp;2&nbsp;(f): CSD = 3. April 2021"><img src="images/3_csd_abr_2021.png" class="img-fluid figure-img" data-ref-parent="fig-cs-true"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csd-3-21-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(f) CSD = 3. April 2021
</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell-subref quarto-layout-cell" data-ref-parent="fig-cs-true" style="flex-basis: 50.0%;justify-content: flex-start;">
<div id="fig-csd-3-20" class="lightbox quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-subfloat-fig figure">
<div aria-describedby="fig-csd-3-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<a href="images/3_csd_jul_2020.png" class="lightbox" data-gallery="fig-cs-true" title="Figure&nbsp;2&nbsp;(g): CSD = 3. July 2020"><img src="images/3_csd_jul_2020.png" class="img-fluid figure-img" data-ref-parent="fig-cs-true"></a>
</div>
<figcaption class="quarto-float-caption-bottom quarto-subfloat-caption quarto-subfloat-fig" id="fig-csd-3-20-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
(g) CSD = 3. July 2020
</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cs-true-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Corte Seletivo (CS) TRUE
</figcaption>
</figure>
</div>
<div id="fig-cr-false" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cr-false-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_cr_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-13" title="CR = 0. July 2022"><img src="images/0_cr_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 0. July 2022</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_cr_jul_23.png" class="lightbox" data-gallery="quarto-lightbox-gallery-14" title="CR = 0. July 2023"><img src="images/0_cr_jul_23.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 0. July 2023</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_csd_ago_21.png" class="lightbox" data-gallery="quarto-lightbox-gallery-15" title="CSD = 1. August 2021"><img src="images/1_csd_ago_21.png" class="img-fluid figure-img"></a></p>
<figcaption>CSD = 1. August 2021</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_csd_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-16" title="CSD = 1. July 2022"><img src="images/1_csd_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CSD = 1. July 2022</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/2_veg_ago_21.png" class="lightbox" data-gallery="quarto-lightbox-gallery-17" title="VEG = 2. August 2021"><img src="images/2_veg_ago_21.png" class="img-fluid figure-img"></a></p>
<figcaption>VEG = 2. August 2021</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/2_veg_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-18" title="VEG = 2. July 2022"><img src="images/2_veg_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>VEG = 2. July 2022</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/FALSE_cr_ago_17.png" class="lightbox" data-gallery="quarto-lightbox-gallery-19" title="CR FALSE. August 2017"><img src="images/FALSE_cr_ago_17.png" class="img-fluid figure-img"></a></p>
<figcaption>CR FALSE. August 2017</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/FALSE_cr_jul_18.png" class="lightbox" data-gallery="quarto-lightbox-gallery-20" title="CR FALSE. July 2018"><img src="images/FALSE_cr_jul_18.png" class="img-fluid figure-img"></a></p>
<figcaption>CR FALSE. July 2018</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cr-false-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Desmatamento (CR) FALSE
</figcaption>
</figure>
</div>
<div id="fig-cr-true" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cr-true-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_cr_jul_19.png" class="lightbox" data-gallery="quarto-lightbox-gallery-21" title="CR = 0. July 2019"><img src="images/0_cr_jul_19.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 0. July 2019</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_cr_jul_20.png" class="lightbox" data-gallery="quarto-lightbox-gallery-22" title="CR = 0. July 2020"><img src="images/0_cr_jul_20.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 0. July 2020</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_cr_jul_21.png" class="lightbox" data-gallery="quarto-lightbox-gallery-23" title="CR = 1. July 2021"><img src="images/1_cr_jul_21.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 1. July 2021</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_cr_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-24" title="CR = 1. July 2022"><img src="images/1_cr_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 1. July 2022</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/2_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-25" title="CR = 2. July 2022"><img src="images/2_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 2. July 2022</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/2_jul_23.png" class="lightbox" data-gallery="quarto-lightbox-gallery-26" title="CR = 2. July 2023"><img src="images/2_jul_23.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 2. July 2023</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/3_jul_18.png" class="lightbox" data-gallery="quarto-lightbox-gallery-27" title="CR = 3. July 2018"><img src="images/3_jul_18.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 3. July 2018</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/3_jul_19.png" class="lightbox" data-gallery="quarto-lightbox-gallery-28" title="CR = 3. July 2019"><img src="images/3_jul_19.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 3. July 2019</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cr-true-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Desmatamento (CR) TRUE
</figcaption>
</figure>
</div>
<div id="fig-cqf-false" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cqf-false-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_CQF_dez_2015.png" class="lightbox" data-gallery="quarto-lightbox-gallery-29" title="CQF = 0. December 2015"><img src="images/0_CQF_dez_2015.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 0. December 2015</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_CQF_jul_2017.png" class="lightbox" data-gallery="quarto-lightbox-gallery-30" title="CQF = 0. July 2017"><img src="images/0_CQF_jul_2017.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 0. July 2017</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_CQF_set_2016.png" class="lightbox" data-gallery="quarto-lightbox-gallery-31" title="CQF = 0. September 2016"><img src="images/0_CQF_set_2016.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 0. September 2016</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_CQF_dez_2015.png" class="lightbox" data-gallery="quarto-lightbox-gallery-32" title="CQF = 1. December 2015"><img src="images/1_CQF_dez_2015.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 1. December 2015</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_CQF_out_2016.png" class="lightbox" data-gallery="quarto-lightbox-gallery-33" title="CQF = 1. October 2016"><img src="images/1_CQF_out_2016.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 1. October 2016</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_CQF_dez_2015-01.png" class="lightbox" data-gallery="quarto-lightbox-gallery-34" title="CQF = 1. December 2015"><img src="images/1_CQF_dez_2015-01.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 1. December 2015</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/2_veg_jul_2016.png" class="lightbox" data-gallery="quarto-lightbox-gallery-35" title="VEG = 2. July 2016"><img src="images/2_veg_jul_2016.png" class="img-fluid figure-img"></a></p>
<figcaption>VEG = 2. July 2016</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/2_veg_jul_2017.png" class="lightbox" data-gallery="quarto-lightbox-gallery-36" title="VEG = 2. July 2017"><img src="images/2_veg_jul_2017.png" class="img-fluid figure-img"></a></p>
<figcaption>VEG = 2. July 2017</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/3_cr_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-37" title="CR = 3. July 2022"><img src="images/3_cr_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 3. July 2022</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/3_cr_set_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-38" title="CR = 3. September 2022"><img src="images/3_cr_set_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 3. September 2022</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/3_cr_jul_23.png" class="lightbox" data-gallery="quarto-lightbox-gallery-39" title="CR = 3. July 2023"><img src="images/3_cr_jul_23.png" class="img-fluid figure-img"></a></p>
<figcaption>CR = 3. July 2023</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/4_varzea_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-40" title="VARZEA = 4. July 2022"><img src="images/4_varzea_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>VARZEA = 4. July 2022</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/4_varzea_out_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-41" title="VARZEA = 4. October 2022"><img src="images/4_varzea_out_22.png" class="img-fluid figure-img"></a></p>
<figcaption>VARZEA = 4. October 2022</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/4_varzea_jun_23.png" class="lightbox" data-gallery="quarto-lightbox-gallery-42" title="VARZEA = 4. Junho 2023"><img src="images/4_varzea_jun_23.png" class="img-fluid figure-img"></a></p>
<figcaption>VARZEA = 4. Junho 2023</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/5_nuvem_jul_2016.png" class="lightbox" data-gallery="quarto-lightbox-gallery-43" title="NUVEM = 5. July 2016"><img src="images/5_nuvem_jul_2016.png" class="img-fluid figure-img"></a></p>
<figcaption>NUVEM = 5. July 2016</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/5_nuvem_juL_2017.png" class="lightbox" data-gallery="quarto-lightbox-gallery-44" title="NUVEM = 5. July 2017"><img src="images/5_nuvem_juL_2017.png" class="img-fluid figure-img"></a></p>
<figcaption>NUVEM = 5. July 2017</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cqf-false-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Fire FALSE
</figcaption>
</figure>
</div>
<div id="fig-cqf-true" class="quarto-layout-panel">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-cqf-true-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/00_cqf_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-45" title="CQF = 00. July 2022"><img src="images/00_cqf_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 00. July 2022</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/00_cqf_set_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-46" title="CQF = 00. September 2022"><img src="images/00_cqf_set_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 00. September 2022</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/00_cqf_jul_23.png" class="lightbox" data-gallery="quarto-lightbox-gallery-47" title="CQF = 00. July 2023"><img src="images/00_cqf_jul_23.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 00. July 2023</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_cqf_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-48" title="CQF = 0. July 2022"><img src="images/0_cqf_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 0. July 2022</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_cqf_set_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-49" title="CQF = 0. September 2022"><img src="images/0_cqf_set_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 0. September 2022</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/0_cqf_jun_23.png" class="lightbox" data-gallery="quarto-lightbox-gallery-50" title="CQF = 0. July 2023"><img src="images/0_cqf_jun_23.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 0. July 2023</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_cqf_jul_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-51" title="CQF = 1. July 2022"><img src="images/1_cqf_jul_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 1. July 2022</figcaption>
</figure>
</div>
</div>
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_cqf_set_22.png" class="lightbox" data-gallery="quarto-lightbox-gallery-52" title="CQF = 1. September 2022"><img src="images/1_cqf_set_22.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 1. September 2022</figcaption>
</figure>
</div>
</div>
</div>
<div class="quarto-layout-row">
<div class="quarto-layout-cell" style="flex-basis: 50.0%;justify-content: flex-start;">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><a href="images/1_cqf_jul_23.png" class="lightbox" data-gallery="quarto-lightbox-gallery-53" title="CQF = 1. July 2023"><img src="images/1_cqf_jul_23.png" class="img-fluid figure-img"></a></p>
<figcaption>CQF = 1. July 2023</figcaption>
</figure>
</div>
</div>
</div>
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-cqf-true-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;6: Fire TRUE
</figcaption>
</figure>
</div>
</section>
<section id="accuracy-by-class" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Accuracy By Class</h1>
<p>The validation using Planet images was based on the protocol pointed out by Dalagnol et al.&nbsp;2023, but without the use of machine learning.</p>
<p>The <a href="#tbl-prob-result" class="quarto-xref">Table&nbsp;17</a> presents the terminologies applied to mapping uncertainties, with their respective result ranges representing each class.</p>
<div id="tbl-prob-result" class="striped hover quarto-float quarto-figure quarto-figure-center anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-prob-result-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;17: Uncertainty Terminology
</figcaption>
<div aria-describedby="tbl-prob-result-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<table class="table-striped table-hover caption-top table">
<colgroup>
<col style="width: 44%">
<col style="width: 55%">
</colgroup>
<thead>
<tr class="header">
<th>Term</th>
<th>Probability of the Result</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Practically certain</td>
<td>99-100% probability</td>
</tr>
<tr class="even">
<td>Very likely</td>
<td>90-100% probability</td>
</tr>
<tr class="odd">
<td>Likely</td>
<td>66-100% probability</td>
</tr>
<tr class="even">
<td>About as likely as not</td>
<td>33-66% probability</td>
</tr>
<tr class="odd">
<td>Unlikely</td>
<td>0-33% probability</td>
</tr>
<tr class="even">
<td>Very unlikely</td>
<td>0-10% probability</td>
</tr>
<tr class="odd">
<td>Exceptionally unlikely</td>
<td>0-1% probability</td>
</tr>
</tbody>
</table>
</div>
</figure>
</div>
<section id="clear-cut-deforestation-cr" class="level2" data-number="5.1">
<h2 data-number="5.1" class="anchored" data-anchor-id="clear-cut-deforestation-cr"><span class="header-section-number">5.1</span> Clear Cut Deforestation (CR)</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorioIPAM_en_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="interpretation" class="level3" data-number="5.1.1">
<h3 data-number="5.1.1" class="anchored" data-anchor-id="interpretation"><span class="header-section-number">5.1.1</span> Interpretation</h3>
<ul>
<li><strong>True Negatives (TN):</strong> 91 cases were correctly classified as non-deforestation.</li>
<li><strong>False Positives (FP):</strong> 655 cases were incorrectly classified as deforestation.</li>
<li><strong>False Negatives (FN):</strong> 1 case was incorrectly classified as non-deforestation.</li>
<li><strong>True Positives (TP):</strong> 1418 cases were correctly classified as deforestation.</li>
</ul>
</section>
<section id="evaluation-metrics" class="level3" data-number="5.1.2">
<h3 data-number="5.1.2" class="anchored" data-anchor-id="evaluation-metrics"><span class="header-section-number">5.1.2</span> Evaluation Metrics</h3>
<ul>
<li><p><strong>Accuracy:</strong> 0.697<br>
Accuracy is the proportion of correct predictions over the total number of predictions. In this case, the model has an accuracy of 69.7%, meaning the model correctly predicted 69.7% of the time.</p></li>
<li><p><strong>Confidence Interval (95% CI):</strong> (0.6772, 0.7163)<br>
The confidence interval for accuracy indicates that, with 95% confidence, the true accuracy of the model is between 67.72% and 71.63%.</p></li>
<li><p><strong>No Information Rate (NIR):</strong> 0.9575<br>
The No Information Rate is the proportion of the largest class group. Here, the class “0” represents 95.75% of the data. This value represents the accuracy that would be achieved by always predicting the most frequent class.</p></li>
<li><p><strong>P-Value [Acc &gt; NIR]:</strong> 1<br>
The p-value associated with testing the hypothesis that the model’s accuracy is greater than the No Information Rate. A p-value of 1 indicates there is no statistical evidence that the model is better than random classification.</p></li>
<li><p><strong>Kappa:</strong> 0.1531<br>
Kappa is a measure comparing the model’s accuracy to the accuracy expected by chance. A value of 0.1531 indicates only a slightly better-than-chance agreement.</p></li>
<li><p><strong>McNemar’s Test (P-Value):</strong> &lt;0.002<br>
McNemar’s test evaluates the symmetry of the model’s errors (type I vs.&nbsp;type II errors). A very small p-value (&lt;2e-16) indicates a significant difference in the false positive and false negative error rates.</p></li>
</ul>
</section>
<section id="sensitivity-and-specificity-metrics" class="level3" data-number="5.1.3">
<h3 data-number="5.1.3" class="anchored" data-anchor-id="sensitivity-and-specificity-metrics"><span class="header-section-number">5.1.3</span> Sensitivity and Specificity Metrics</h3>
<ul>
<li><p><strong>Sensitivity:</strong> 0.98913<br>
Sensitivity, or the true positive rate, is the proportion of positive cases correctly identified by the model. With a value of 98.91%, the model is highly effective at identifying deforestation cases (class 1).</p></li>
<li><p><strong>Specificity:</strong> 0.68403<br>
Specificity is the proportion of negative cases correctly identified. At 68.4%, the model is moderately effective at identifying non-deforestation cases (class 0).</p></li>
<li><p><strong>Positive Predictive Value (Pos Pred Value):</strong> 0.12198<br>
Positive predictive value indicates the proportion of true positives among all cases predicted as positive. Here, only 12.2% of deforestation predictions are actually correct.</p></li>
<li><p><strong>Negative Predictive Value (Neg Pred Value):</strong> 0.99930<br>
Negative predictive value is the proportion of true negatives among all cases predicted as negative. With 99.93%, the model is highly effective at correctly predicting non-deforestation.</p></li>
<li><p><strong>Prevalence:</strong> 0.04249<br>
Prevalence is the proportion of actual positive cases in the data sample. Only 4.25% of the cases involve deforestation.</p></li>
<li><p><strong>Detection Rate:</strong> 0.04203<br>
The detection rate is the proportion of actual positive cases correctly detected by the model.</p></li>
<li><p><strong>Detection Prevalence:</strong> 0.34457<br>
Detection prevalence is the proportion of cases predicted as positive by the model.</p></li>
<li><p><strong>Balanced Accuracy:</strong> 0.83658<br>
Balanced accuracy is the average of sensitivity and specificity. At 83.66%, the model shows balanced performance in correctly identifying both positive and negative cases.</p></li>
</ul>
</section>
<section id="conclusion" class="level3" data-number="5.1.4">
<h3 data-number="5.1.4" class="anchored" data-anchor-id="conclusion"><span class="header-section-number">5.1.4</span> Conclusion</h3>
<p>The model is highly sensitive (good at detecting deforestation) but has low specificity and positive predictive value, indicating it makes many false positive errors (predicting deforestation when there isn’t any). Accuracy is moderate, and Kappa suggests the model performs only slightly better than chance. Due to the very low p-value from McNemar’s test, there is a significant bias in the type of errors made by the model. In summary, the model is good at detecting almost all deforestation cases.</p>
<p><strong>With this accuracy value (69.7%), the model result is considered likely to occur (<a href="#tbl-prob-result" class="quarto-xref">Table&nbsp;17</a>).</strong></p>
</section>
</section>
<section id="burn-scar-cqf-1" class="level2" data-number="5.2">
<h2 data-number="5.2" class="anchored" data-anchor-id="burn-scar-cqf-1"><span class="header-section-number">5.2</span> Burn Scar (CQF)</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorioIPAM_en_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="interpretation-1" class="level3" data-number="5.2.1">
<h3 data-number="5.2.1" class="anchored" data-anchor-id="interpretation-1"><span class="header-section-number">5.2.1</span> Interpretation</h3>
<ul>
<li><strong>True Negative (TN):</strong> 53 cases were correctly classified as non-burn scar.</li>
<li><strong>False Positive (FP):</strong> 259 cases were incorrectly classified as burn scar.</li>
<li><strong>False Negative (FN):</strong> 1 case was incorrectly classified as non-burn scar.</li>
<li><strong>True Positive (TP):</strong> 1441 cases were correctly classified as burn scar.</li>
</ul>
</section>
<section id="evaluation-metrics-1" class="level3" data-number="5.2.2">
<h3 data-number="5.2.2" class="anchored" data-anchor-id="evaluation-metrics-1"><span class="header-section-number">5.2.2</span> Evaluation Metrics</h3>
<ul>
<li><p><strong>Accuracy:</strong> 0.8518 (85.18%)<br>
The model has good overall performance, with 85.18% correct predictions.</p></li>
<li><p><strong>Kappa:</strong> 0.2503<br>
Indicates a slight agreement between the model’s predictions and the actual classification, adjusted for the agreement that occurs by chance.</p></li>
<li><p><strong>McNemar’s Test P-Value:</strong> &lt;0.0002<br>
Shows a statistically significant difference between false positives and false negatives.</p></li>
</ul>
</section>
<section id="sensitivity-and-specificity-metrics-1" class="level3" data-number="5.2.3">
<h3 data-number="5.2.3" class="anchored" data-anchor-id="sensitivity-and-specificity-metrics-1"><span class="header-section-number">5.2.3</span> Sensitivity and Specificity Metrics</h3>
<ul>
<li><p><strong>Sensitivity:</strong> 0.98148 (98.15%)<br>
The model is highly effective at detecting burn scars when they are truly present.</p></li>
<li><p><strong>Specificity:</strong> 0.84765 (84.77%)<br>
Indicates that the model is good at correctly identifying negative cases (no burn scar).</p></li>
<li><p><strong>Positive Predictive Value (PPV):</strong> 0.16987 (16.99%)<br>
Most of the positive predictions made by the model are false positives, indicating low precision in positive predictions.</p></li>
<li><p><strong>Negative Predictive Value (NPV):</strong> 0.99931 (99.93%)<br>
Highly reliable when the model predicts the absence of a burn scar.</p></li>
<li><p><strong>Prevalence:</strong> 0.03079 (3.08%)<br>
Indicates that burn scars are relatively rare in the data.</p></li>
<li><p><strong>Detection Rate:</strong> 0.03022 (3.02%)<br>
Proportion of actual positive cases correctly detected by the model.</p></li>
<li><p><strong>Detection Prevalence:</strong> 0.17788 (17.79%)<br>
Proportion of cases predicted as positive by the model.</p></li>
<li><p><strong>Balanced Accuracy:</strong> 0.91456 (91.46%)<br>
The average of Sensitivity and Specificity, useful for imbalanced datasets.</p></li>
</ul>
</section>
<section id="conclusion-1" class="level3" data-number="5.2.4">
<h3 data-number="5.2.4" class="anchored" data-anchor-id="conclusion-1"><span class="header-section-number">5.2.4</span> Conclusion</h3>
<p>The model is highly sensitive and has good overall accuracy, but low specificity and positive predictive value indicate a tendency to predict false positives. To improve, the model may need adjustments to increase the precision of positive predictions, especially in a context where false positives may have significant implications.</p>
<p><strong>With this accuracy value (85.18%), the model result is considered likely to occur (<a href="#tbl-prob-result" class="quarto-xref">Table&nbsp;17</a>).</strong></p>
</section>
</section>
<section id="disorderly-selective-logging-csd" class="level2" data-number="5.3">
<h2 data-number="5.3" class="anchored" data-anchor-id="disorderly-selective-logging-csd"><span class="header-section-number">5.3</span> Disorderly Selective Logging (CSD)</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorioIPAM_en_files/figure-html/unnamed-chunk-12-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="interpretation-2" class="level3" data-number="5.3.1">
<h3 data-number="5.3.1" class="anchored" data-anchor-id="interpretation-2"><span class="header-section-number">5.3.1</span> Interpretation</h3>
<ul>
<li><strong>True Negatives (TN):</strong> 2 cases were correctly classified as non-selective logging.</li>
<li><strong>False Positives (FP):</strong> 24 cases were incorrectly classified as disorderly selective logging.</li>
<li><strong>False Negatives (FN):</strong> 0 cases were incorrectly classified as non-disorderly selective logging.</li>
<li><strong>True Positives (TP):</strong> 101 cases were correctly classified as disorderly selective logging.</li>
</ul>
</section>
<section id="evaluation-metrics-2" class="level3" data-number="5.3.2">
<h3 data-number="5.3.2" class="anchored" data-anchor-id="evaluation-metrics-2"><span class="header-section-number">5.3.2</span> Evaluation Metrics</h3>
<ul>
<li><p><strong>Accuracy:</strong> 0.811 (81.1%)<br>
Accuracy indicates the proportion of correct predictions (both ‘0’ and ‘1’) over the total predictions. In this case, 81.1% of the model’s predictions are correct.</p></li>
<li><p><strong>95% Confidence Interval for Accuracy:</strong> (0.732, 0.875)<br>
This interval suggests 95% confidence that the true accuracy of the model lies between 73.2% and 87.5%.</p></li>
<li><p><strong>No Information Rate (NIR):</strong> 0.9843 (98.43%)<br>
NIR is the proportion of correct predictions that would be made if the model always predicted the most common class. In this case, class ‘1’ (presence of CSD) is the most common.</p></li>
<li><p><strong>P-Value [Acc &gt; NIR]:</strong> 1<br>
This value indicates the probability that the model is better than a model that always predicts the majority class. A value of 1 suggests that the model is not significantly better than a naive model that always predicts the majority class.</p></li>
<li><p><strong>Kappa:</strong> 0.117<br>
Kappa measures the agreement between the model’s predictions and the actual classifications, adjusted for chance agreement. A value of 0.117 indicates very low agreement beyond chance.</p></li>
<li><p><strong>McNemar’s Test P-Value:</strong> 0.000002668<br>
The McNemar test is used to evaluate the significance of differences between the two classifications (prediction ‘0’ vs ‘1’). A very low p-value indicates a significant difference between the ‘0’ and ‘1’ classifications.</p></li>
</ul>
</section>
<section id="sensitivity-and-specificity-metrics-2" class="level3" data-number="5.3.3">
<h3 data-number="5.3.3" class="anchored" data-anchor-id="sensitivity-and-specificity-metrics-2"><span class="header-section-number">5.3.3</span> Sensitivity and Specificity Metrics</h3>
<ul>
<li><p><strong>Sensitivity (Recall for class ‘0’):</strong> 1.00000 (100%)<br>
Sensitivity indicates the model’s ability to correctly predict class ‘0’. In this case, the model detects all ‘0’ cases (absence of CSD) correctly.</p></li>
<li><p><strong>Specificity (Recall for class ‘1’):</strong> 0.80800 (80.8%)<br>
Specificity indicates the model’s ability to correctly predict class ‘1’. In this case, 80.8% of ‘1’ cases (presence of CSD) are correctly identified.</p></li>
<li><p><strong>Positive Predictive Value (PPV or Precision for class ‘0’):</strong> 0.07692 (7.692%)<br>
PPV indicates the proportion of ‘0’ predictions that are truly ‘0’. Here, only 7.692% of ‘0’ predictions are correct.</p></li>
<li><p><strong>Negative Predictive Value (NPV for class ‘1’):</strong> 1.00000 (100%)<br>
NPV indicates the proportion of ‘1’ predictions that are truly ‘1’. In this case, all ‘1’ predictions are correct.</p></li>
<li><p><strong>Prevalence:</strong> 0.01575 (1.575%)<br>
Prevalence is the proportion of actual class ‘0’ cases. In this dataset, 1.575% of the samples are class ‘0’.</p></li>
<li><p><strong>Detection Rate (for class ‘0’):</strong> 0.01575 (1.575%)<br>
The detection rate is the proportion of positive cases correctly identified. It coincides with prevalence here.</p></li>
<li><p><strong>Detection Prevalence (for class ‘0’):</strong> 0.20472 (20.472%)<br>
Detection prevalence is the proportion of all predictions that are for class ‘0’. In this case, 20.472% of the model’s predictions were for class ‘0’.</p></li>
<li><p><strong>Balanced Accuracy:</strong> 0.90400 (90.4%)<br>
Balanced accuracy is the average of sensitivity and specificity. It reflects the model’s ability to fairly identify both classes. In this case, it is high, indicating good overall performance.</p></li>
</ul>
</section>
<section id="conclusion-2" class="level3" data-number="5.3.4">
<h3 data-number="5.3.4" class="anchored" data-anchor-id="conclusion-2"><span class="header-section-number">5.3.4</span> Conclusion</h3>
<p>The model shows high overall accuracy (81.1%), but this may be misleading due to the highly imbalanced class distribution (class ‘1’ dominant). The high sensitivity and negative predictive value suggest that the model is good at detecting class ‘1’ (presence of CSD), but has significant difficulty in correctly predicting class ‘0’ (absence of CSD), as indicated by the low specificity and positive predictive value. The low Kappa value also indicates that the model does not perform much better than chance when adjusted for class distribution.</p>
<p><strong>With this accuracy value (81.1%), the model result is considered likely to occur (<a href="#tbl-prob-result" class="quarto-xref">Table&nbsp;17</a>).</strong></p>
</section>
</section>
<section id="geometric-selective-logging-csg" class="level2" data-number="5.4">
<h2 data-number="5.4" class="anchored" data-anchor-id="geometric-selective-logging-csg"><span class="header-section-number">5.4</span> Geometric Selective Logging (CSG)</h2>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorioIPAM_en_files/figure-html/unnamed-chunk-14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="interpretation-3" class="level3" data-number="5.4.1">
<h3 data-number="5.4.1" class="anchored" data-anchor-id="interpretation-3"><span class="header-section-number">5.4.1</span> Interpretation</h3>
<ul>
<li><p><strong>True Negatives (TN):</strong> 2 cases were correctly classified as non-geometric selective logging.</p></li>
<li><p><strong>False Positives (FP):</strong> 5 cases were incorrectly classified as geometric selective logging.</p></li>
<li><p><strong>False Negatives (FN):</strong> 0 cases were incorrectly classified as non-geometric selective logging.</p></li>
<li><p><strong>True Positives (TP):</strong> 69 cases were correctly classified as geometric selective logging.</p></li>
</ul>
</section>
<section id="evaluation-metrics-3" class="level3" data-number="5.4.2">
<h3 data-number="5.4.2" class="anchored" data-anchor-id="evaluation-metrics-3"><span class="header-section-number">5.4.2</span> Evaluation Metrics</h3>
<ul>
<li><p><strong>Accuracy:</strong> 0.9342 (93.42%)<br>
Accuracy indicates the proportion of all correct predictions (TN + TP) relative to the total number of samples. In this case, the model correctly classified 93.42% of the examples.</p></li>
<li><p><strong>95% CI (Confidence Interval for Accuracy):</strong> (0.8531, 0.9783)<br>
The confidence interval indicates the range within which the true accuracy of the model lies, with 95% confidence. This suggests that the model’s true accuracy is between 85.31% and 97.83%.</p></li>
<li><p><strong>No Information Rate (NIR):</strong> 0.9737 (97.37%)<br>
The NIR represents the accuracy that would be achieved if the model always predicted the most common class (class 1, geometric selective logging, which appears in 97.37% of the cases).</p></li>
<li><p><strong>P-Value [Acc &gt; NIR]:</strong> 0.98486<br>
This p-value tests the hypothesis that the model’s accuracy is better than the NIR. A p-value greater than 0.05 suggests no statistical evidence that the model is better than a naive classification that always predicts the most common class.</p></li>
<li><p><strong>Kappa:</strong> 0.4207<br>
The Kappa coefficient measures the degree of agreement between the model’s predictions and the actual classifications, adjusted for agreement that would occur by chance. A value of 0.4207 indicates moderate, but not excellent, agreement.</p></li>
<li><p><strong>McNemar’s Test P-Value:</strong> 0.07364<br>
The McNemar test is used to assess whether the error rates between two classifications are significantly different. A p-value greater than 0.05 indicates no statistically significant difference between the error rates of the two groups.</p></li>
</ul>
</section>
<section id="sensitivity-and-specificity-metrics-3" class="level3" data-number="5.4.3">
<h3 data-number="5.4.3" class="anchored" data-anchor-id="sensitivity-and-specificity-metrics-3"><span class="header-section-number">5.4.3</span> Sensitivity and Specificity Metrics</h3>
<ul>
<li><p><strong>Sensitivity:</strong> 1.00000 (100%)<br>
Sensitivity is the model’s ability to correctly identify positive cases (geometric selective logging). A sensitivity of 100% means the model correctly identified all geometric selective logging cases.</p></li>
<li><p><strong>Specificity:</strong> 0.93243 (93.24%)<br>
Specificity is the model’s ability to correctly identify negative cases (non-geometric selective logging). A value of 93.24% indicates that the model was able to correctly identify most non-geometric selective logging cases.</p></li>
<li><p><strong>Positive Predictive Value (PPV):</strong> 0.28571 (28.57%)<br>
The positive predictive value represents the proportion of correct positive predictions among all positive predictions. A value of 28.57% indicates that among all times the model predicted geometric selective logging, only 28.57% were correct.</p></li>
<li><p><strong>Negative Predictive Value (NPV):</strong> 1.00000 (100%)<br>
The negative predictive value represents the proportion of correct negative predictions among all negative predictions. A value of 100% means that all non-geometric selective logging predictions were correct.</p></li>
<li><p><strong>Prevalence:</strong> 0.02632 (2.63%)<br>
Prevalence indicates the proportion of actual positive cases in the total population. Only 2.63% of the cases are geometric selective logging.</p></li>
<li><p><strong>Detection Rate:</strong> 0.02632 (2.63%)<br>
The detection rate indicates the proportion of positive cases correctly identified by the model.</p></li>
<li><p><strong>Detection Prevalence:</strong> 0.09211 (9.21%)<br>
The detection prevalence indicates the proportion of all predictions made as positive by the model.</p></li>
<li><p><strong>Balanced Accuracy:</strong> 0.96622 (96.62%)<br>
Balanced accuracy is the average of sensitivity and specificity. A value of 96.62% indicates that the model has a good balance between detecting positive and negative cases.</p></li>
</ul>
</section>
<section id="conclusion-3" class="level3" data-number="5.4.4">
<h3 data-number="5.4.4" class="anchored" data-anchor-id="conclusion-3"><span class="header-section-number">5.4.4</span> Conclusion</h3>
<p>The model shows high accuracy and sensitivity, suggesting it is very good at identifying geometric selective logging cases. However, the low positive predictive value (28.57%) indicates a high rate of false positives, suggesting that the model often misclassifies cases as geometric selective logging when they are not. The Kappa of 0.4207 suggests moderate agreement beyond chance. Specificity is high, but the McNemar test and the p-value for accuracy relative to NIR suggest that the model is not significantly better than a classification based on the majority class.</p>
<p><strong>With this accuracy (93.42%), the model is considered very likely to occur (<a href="#tbl-prob-result" class="quarto-xref">Table&nbsp;17</a>).</strong></p>
</section>
</section>
</section>
<section id="global-accuracy" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> Global Accuracy</h1>
<div class="cell">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="relatorioIPAM_en_files/figure-html/acuracia-geral-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="confusion-matrix-interpretation" class="level2" data-number="6.1">
<h2 data-number="6.1" class="anchored" data-anchor-id="confusion-matrix-interpretation"><span class="header-section-number">6.1</span> Confusion Matrix Interpretation</h2>
<ul>
<li><strong>CQF</strong>: 1441 instances were correctly classified as CQF, while 55 instances of VEG were incorrectly classified as CQF.</li>
<li><strong>CR</strong>: 1418 instances were correctly classified as CR, while 862 instances of VEG were incorrectly classified as CR.</li>
<li><strong>CSD_1</strong>: 101 instances were correctly classified as CSD_1.</li>
<li><strong>CSG_2</strong>: 69 instances were correctly classified as CSG_2.</li>
<li><strong>VEG</strong>: 148 instances were correctly classified as VEG, but many instances (55 for CQF and 862 for CR) were incorrectly classified as other classes.</li>
</ul>
</section>
<section id="evaluation-metrics-4" class="level2" data-number="6.2">
<h2 data-number="6.2" class="anchored" data-anchor-id="evaluation-metrics-4"><span class="header-section-number">6.2</span> Evaluation Metrics</h2>
<ul>
<li><strong>Accuracy:</strong> 0.7707<br>
This means that approximately 77% of the model’s predictions are correct.</li>
<li><strong>95% CI (Confidence Interval for Accuracy):</strong> (0.7576, 0.7835)<br>
Indicates that the true accuracy of the model lies between 75.76% and 78.35% with 95% confidence.</li>
<li><strong>No Information Rate (NIR):</strong> 0.5531<br>
Represents the proportion of the largest class in the dataset. If the model always predicted the most frequent class, it would have an accuracy of 55.31%.</li>
<li><strong>P-Value [Acc &gt; NIR]:</strong> &lt; 2.2e-16<br>
Indicates that the model’s accuracy is significantly higher than the no-information rate, suggesting the model has predictive value.</li>
<li><strong>Kappa:</strong> 0.6588<br>
This metric accounts for accuracy and chance. A value of 0.6588 indicates substantial agreement beyond chance.</li>
<li><strong>McNemar’s Test P-Value:</strong> NA<br>
This test may not be applicable due to the lack of sufficient data for comparing type I and type II errors.</li>
</ul>
</section>
<section id="sensitivity-and-specificity-metrics-4" class="level2" data-number="6.3">
<h2 data-number="6.3" class="anchored" data-anchor-id="sensitivity-and-specificity-metrics-4"><span class="header-section-number">6.3</span> Sensitivity and Specificity Metrics</h2>
<p>For each class, several key metrics are as follows:</p>
<ul>
<li><strong>Sensitivity (Recall):</strong> The model’s ability to correctly identify positive instances of a specific class.
<ul>
<li><strong>CQF:</strong> 0.9632. The model correctly identified 96.32% of CQF instances.</li>
<li><strong>CR:</strong> 0.6219. The model correctly identified 62.19% of CR instances, which is relatively low.</li>
<li><strong>CSD_1:</strong> 0.8145. The model correctly identified 81.45% of CSD_1 instances.</li>
<li><strong>CSG_2:</strong> 0.9583. The model correctly identified 95.83% of CSG_2 instances.</li>
<li><strong>VEG:</strong> 0.9867. The model correctly identified 98.67% of VEG instances.</li>
</ul></li>
<li><strong>Specificity:</strong> The model’s ability to correctly identify negative instances of a specific class.
<ul>
<li>Specificity is very high for all classes except VEG, where it is 0.76259.</li>
</ul></li>
<li><strong>Positive Predictive Value (PPV):</strong> The proportion of true positives among all predicted positives.
<ul>
<li><strong>CQF:</strong> 0.9993. Almost all instances predicted as CQF are actually CQF.</li>
<li><strong>VEG:</strong> 0.1357. Only 13.57% of instances predicted as VEG are truly VEG, indicating many incorrect VEG predictions.</li>
</ul></li>
<li><strong>Negative Predictive Value (NPV):</strong> The proportion of true negatives among all predicted negatives.
<ul>
<li>Generally high, indicating that instances not belonging to a given class are correctly identified as not belonging to that class.</li>
</ul></li>
<li><strong>Prevalence:</strong> The proportion of actual positive instances of each class in the dataset.
<ul>
<li><strong>CR</strong> has the highest prevalence (55.31%).</li>
</ul></li>
<li><strong>Balanced Accuracy:</strong> The average of sensitivity and specificity for a class, useful for imbalanced data.
<ul>
<li>High for all classes except CR, where it is moderate (0.8107).</li>
</ul></li>
</ul>
</section>
<section id="conclusion-4" class="level2" data-number="6.4">
<h2 data-number="6.4" class="anchored" data-anchor-id="conclusion-4"><span class="header-section-number">6.4</span> Conclusion</h2>
<p>The model shows good overall accuracy (77.07%) and high sensitivity and specificity for most classes, except CR, which has lower sensitivity (62.19%). The VEG class has a very low positive predictive value (13.57%), indicating that the model often incorrectly predicts other classes as VEG. Balanced accuracy is high across the board, suggesting the model performs well overall, despite some areas for improvement, particularly in correctly predicting the VEG and CR classes.</p>
<p><strong>With this accuracy (77.07%), the model result is considered likely to occur (<a href="#tbl-prob-result" class="quarto-xref">Table&nbsp;17</a>).</strong></p>
</section>
</section>
<section id="uncertainty-calculation" class="level1" data-number="7">
<h1 data-number="7"><span class="header-section-number">7</span> Uncertainty Calculation</h1>
<section id="mapping-uncertainties" class="level2" data-number="7.1">
<h2 data-number="7.1" class="anchored" data-anchor-id="mapping-uncertainties"><span class="header-section-number">7.1</span> Mapping Uncertainties</h2>
<p>Based on the data reviewed by the analyst, and following the methodology suggested by Olofsson et al.&nbsp;(2014), uncertainty percentages were calculated by considering the areas that were validated and sampled as incorrect during the visual interpretation process. Below, the data is presented by class/year.</p>
<div class="cell">
<div class="cell-output-display">
<table class="caption-top table table-sm table-striped small">
<caption>Porcentagem por classe/ano. CR = Desmatamento, CQF = Cicatriz de Queimada, CSD = Corte Seletivo Desordenado, CSG = Corte Seletivo Geométrico.</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Class</th>
<th style="text-align: right;">Area (ha) label = 0</th>
<th style="text-align: right;">Uncertainty (%) label = 0</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">CQF_2017</td>
<td style="text-align: right;">133932.16</td>
<td style="text-align: right;">0.50</td>
</tr>
<tr class="even">
<td style="text-align: left;">CQF_2018</td>
<td style="text-align: right;">11538.44</td>
<td style="text-align: right;">0.03</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CQF_2019</td>
<td style="text-align: right;">557.47</td>
<td style="text-align: right;">0.16</td>
</tr>
<tr class="even">
<td style="text-align: left;">CQF_2020</td>
<td style="text-align: right;">2290.90</td>
<td style="text-align: right;">0.02</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CQF_2021</td>
<td style="text-align: right;">2431.31</td>
<td style="text-align: right;">0.03</td>
</tr>
<tr class="even">
<td style="text-align: left;">CQF_2022</td>
<td style="text-align: right;">586.60</td>
<td style="text-align: right;">0.05</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CQF_2023</td>
<td style="text-align: right;">445.41</td>
<td style="text-align: right;">0.02</td>
</tr>
<tr class="even">
<td style="text-align: left;">CR_2017</td>
<td style="text-align: right;">529.76</td>
<td style="text-align: right;">0.17</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CR_2018</td>
<td style="text-align: right;">1172.53</td>
<td style="text-align: right;">0.26</td>
</tr>
<tr class="even">
<td style="text-align: left;">CR_2019</td>
<td style="text-align: right;">123.31</td>
<td style="text-align: right;">0.16</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CR_2020</td>
<td style="text-align: right;">737.04</td>
<td style="text-align: right;">0.21</td>
</tr>
<tr class="even">
<td style="text-align: left;">CR_2021</td>
<td style="text-align: right;">625.27</td>
<td style="text-align: right;">0.11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CR_2022</td>
<td style="text-align: right;">249.44</td>
<td style="text-align: right;">0.08</td>
</tr>
<tr class="even">
<td style="text-align: left;">CR_2023</td>
<td style="text-align: right;">1497.24</td>
<td style="text-align: right;">0.35</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CSD_2017</td>
<td style="text-align: right;">1716.77</td>
<td style="text-align: right;">0.36</td>
</tr>
<tr class="even">
<td style="text-align: left;">CSD_2018</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CSD_2019</td>
<td style="text-align: right;">24.24</td>
<td style="text-align: right;">0.01</td>
</tr>
<tr class="even">
<td style="text-align: left;">CSD_2020</td>
<td style="text-align: right;">2279.42</td>
<td style="text-align: right;">0.11</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CSD_2021</td>
<td style="text-align: right;">1493.61</td>
<td style="text-align: right;">0.35</td>
</tr>
<tr class="even">
<td style="text-align: left;">CSD_2022</td>
<td style="text-align: right;">1837.12</td>
<td style="text-align: right;">0.09</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CSD_2023</td>
<td style="text-align: right;">5559.20</td>
<td style="text-align: right;">0.37</td>
</tr>
<tr class="even">
<td style="text-align: left;">CSG_2017</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CSG_2018</td>
<td style="text-align: right;">0.00</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="even">
<td style="text-align: left;">CSG_2019</td>
<td style="text-align: right;">968.62</td>
<td style="text-align: right;">0.30</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CSG_2020</td>
<td style="text-align: right;">436.57</td>
<td style="text-align: right;">0.13</td>
</tr>
<tr class="even">
<td style="text-align: left;">CSG_2021</td>
<td style="text-align: right;">14.63</td>
<td style="text-align: right;">0.00</td>
</tr>
<tr class="odd">
<td style="text-align: left;">CSG_2022</td>
<td style="text-align: right;">339.07</td>
<td style="text-align: right;">0.04</td>
</tr>
<tr class="even">
<td style="text-align: left;">CSG_2023</td>
<td style="text-align: right;">461.88</td>
<td style="text-align: right;">0.04</td>
</tr>
</tbody>
</table>
</div>
</div>
</section>
<section id="monte-carlo-uncertainty-calculation" class="level2" data-number="7.2">
<h2 data-number="7.2" class="anchored" data-anchor-id="monte-carlo-uncertainty-calculation"><span class="header-section-number">7.2</span> Monte Carlo Uncertainty Calculation</h2>
<p>Monte Carlo simulation is a powerful technique that models variability and uncertainty of environmental variables, such as in this context of carbon emissions estimates in Pará forests. Various sources of uncertainty are present, including biomass estimates, deforestation, fire, and emission factors.</p>
</section>
<section id="procedures-for-monte-carlo-simulation-in-r" class="level2" data-number="7.3">
<h2 data-number="7.3" class="anchored" data-anchor-id="procedures-for-monte-carlo-simulation-in-r"><span class="header-section-number">7.3</span> Procedures for Monte Carlo Simulation in <em>R</em></h2>
<ol type="1">
<li><p><strong>Data Collection and Preparation</strong><br>
The first step involves collecting and preparing the data. In the case of forest and carbon emission analysis, this includes geospatial layers of biomass and deforestation data provided by the contractor. For zonal analyses, the <a href="https://isciences.gitlab.io/exactextractr/index.html"><em>exactextractr</em></a> package was used to summarize the raster data sent within the polygons (<a href="#tbl-classes-atividades" class="quarto-xref">Table&nbsp;1</a>).</p>
<ul>
<li><strong>Required Packages</strong>:
<ul>
<li><a href="https://isciences.gitlab.io/exactextractr/index.html"><em>exactextractr</em></a>: for zonal data summarization.</li>
<li><a href="https://r-spatial.github.io/sf/"><em>sf</em></a> and <a href="https://rspatial.github.io/terra/index.html"><em>terra</em></a>: for spatial data manipulation.</li>
<li><a href="https://dplyr.tidyverse.org/"><em>dplyr</em></a>: for tabular data manipulation.</li>
</ul></li>
</ul>
<p>The <em>exactextractr</em> package facilitates obtaining zonal statistics for each polygon overlapping the shapefile. To calculate means, standard deviations, and standard errors, the <em>exact_extract()</em> function is used. It returns a series of statistics for each polygon defined in the <em>sf</em> object, calculating weighted means, standard deviations, and more, depending on the overlapping area.</p></li>
</ol>
<p>Example usage of the <em>exactextractr</em> package:</p>
<div class="sourceCode" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: exemplo-zonal</span></span>
<span id="cb2-2"><a href="#cb2-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb2-3"><a href="#cb2-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(terra)</span>
<span id="cb2-4"><a href="#cb2-4" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(sf)</span>
<span id="cb2-5"><a href="#cb2-5" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(exactextractr)</span>
<span id="cb2-6"><a href="#cb2-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-7"><a href="#cb2-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Reading raster data</span></span>
<span id="cb2-8"><a href="#cb2-8" aria-hidden="true" tabindex="-1"></a>raster_data <span class="ot">&lt;-</span> <span class="fu">rast</span>(<span class="st">"path/to/raster_file.tif"</span>)</span>
<span id="cb2-9"><a href="#cb2-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-10"><a href="#cb2-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Reading shapefile (or other vector data)</span></span>
<span id="cb2-11"><a href="#cb2-11" aria-hidden="true" tabindex="-1"></a>polygons <span class="ot">&lt;-</span> <span class="fu">st_read</span>(<span class="st">"path/to/polygons.shp"</span>)</span>
<span id="cb2-12"><a href="#cb2-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb2-13"><a href="#cb2-13" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting mean and standard deviation for each polygon</span></span>
<span id="cb2-14"><a href="#cb2-14" aria-hidden="true" tabindex="-1"></a>results <span class="ot">&lt;-</span> <span class="fu">exact_extract</span>(raster_data, polygons, <span class="fu">c</span>(<span class="st">'mean'</span>, <span class="st">'stdev'</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>The standard error of the mean can be calculated using the standard deviation and the number of pixels contributing to each polygon. This can be done by taking the square root of the sampled pixels and dividing the standard deviation by that value.</p>
<p>Example of calculating standard error for each polygon:</p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a><span class="co">#| label: exemplo-stderr</span></span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a><span class="co">#| eval: false</span></span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a><span class="co"># Extracting mean, standard deviation, and pixel count</span></span>
<span id="cb3-5"><a href="#cb3-5" aria-hidden="true" tabindex="-1"></a>full_results <span class="ot">&lt;-</span> <span class="fu">exact_extract</span>(raster_data, polygons, <span class="fu">c</span>(<span class="st">'mean'</span>, <span class="st">'stdev'</span>, <span class="st">'count'</span>))</span>
<span id="cb3-6"><a href="#cb3-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-7"><a href="#cb3-7" aria-hidden="true" tabindex="-1"></a><span class="co"># Calculating standard error</span></span>
<span id="cb3-8"><a href="#cb3-8" aria-hidden="true" tabindex="-1"></a>full_results<span class="sc">$</span>std_error <span class="ot">&lt;-</span> full_results<span class="sc">$</span>stdev <span class="sc">/</span> <span class="fu">sqrt</span>(full_results<span class="sc">$</span>count)</span>
<span id="cb3-9"><a href="#cb3-9" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb3-10"><a href="#cb3-10" aria-hidden="true" tabindex="-1"></a><span class="co"># Displaying results with standard error</span></span>
<span id="cb3-11"><a href="#cb3-11" aria-hidden="true" tabindex="-1"></a><span class="fu">head</span>(full_results)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<p>Here, the <code>count</code> function is used to obtain the number of pixels considered in the extraction for each polygon, which is needed to calculate the standard error.</p>
</section>
<section id="arttrees-spreadsheet" class="level2" data-number="7.4">
<h2 data-number="7.4" class="anchored" data-anchor-id="arttrees-spreadsheet"><span class="header-section-number">7.4</span> <em>ART/TREES</em> Spreadsheet</h2>
<p>The <em>ART/TREES</em> spreadsheet <a href="#fn2" class="footnote-ref" id="fnref2" role="doc-noteref"><sup>2</sup></a> is a tool for estimating emission reductions (ER) from forests using the Monte Carlo methodology (MC-4), to estimate avoided emissions from deforestation and forest degradation in REDD+ projects (Reducing Emissions from Deforestation and Forest Degradation).</p>
<section id="key-data-needed-to-populate-the-spreadsheet" class="level3" data-number="7.4.1">
<h3 data-number="7.4.1" class="anchored" data-anchor-id="key-data-needed-to-populate-the-spreadsheet"><span class="header-section-number">7.4.1</span> Key Data Needed to Populate the Spreadsheet</h3>
<p>The spreadsheet requires various types of data to feed the model and perform Monte Carlo simulations. Below are the key data fields that need to be completed based on typical estimation requirements:</p>
<ol type="1">
<li><p><strong>Project Area (Polygon or forest region)</strong></p>
<ul>
<li><strong>Area size</strong>: The total area in hectares to be analyzed. This is essential for calculating emissions in terms of carbon lost or avoided per hectare.</li>
<li><strong>Distribution of forest and deforestation areas</strong>: Information on the initial forest area, areas already deforested, and the deforestation or degradation rate.</li>
</ul></li>
<li><p><strong>Above-Ground Biomass (AGB)</strong></p>
<ul>
<li><strong>Average forest biomass (ton/ha)</strong>: Estimate of above-ground carbon biomass per hectare, in tons.</li>
<li><strong>Biomass distribution</strong>: If different vegetation types or forests exist, biomass distributions for each type may be required.</li>
<li><strong>Biomass uncertainty</strong>: Standard deviation or other uncertainty measures related to biomass.</li>
</ul></li>
<li><p><strong>Biomass-to-Carbon Conversion Factor</strong></p>
<ul>
<li><strong>Conversion factor</strong>: A factor that converts biomass (AGB) into carbon content, usually around 0.47 (i.e., 47% of biomass is carbon).</li>
<li><strong>Uncertainties in this factor</strong>: Possible standard deviations or distributions to represent uncertainty in the conversion factor.</li>
</ul></li>
<li><p><strong>Deforestation Rate</strong></p>
<ul>
<li><strong>Annual deforestation rate (percent or hectares/year)</strong>: The estimate of how much forest will be lost annually in terms of area or percent of the remaining forest.</li>
<li><strong>Deforestation projections</strong>: Future deforestation estimates may be needed if the project involves projections of avoided deforestation scenarios.</li>
<li><strong>Uncertainty in deforestation rate</strong>: Probability distributions to reflect the uncertainty associated with the deforestation rate.</li>
</ul></li>
<li><p><strong>Emission Factors (EF)</strong></p>
<ul>
<li><strong>Carbon emission factor</strong>: Estimate of how much carbon is released per hectare deforested. This typically involves converting stored biomass in the forest into carbon released during deforestation.</li>
<li><strong>Distributions for emission factor</strong>: Uncertainty measures, such as standard deviation, are also needed for the emission factor.</li>
</ul></li>
<li><p><strong>Forest Degradation</strong></p>
<ul>
<li><strong>Degradation rates</strong>: If the project also deals with forest degradation (in addition to deforestation), degradation rates in terms of area affected or the amount of carbon lost need to be included.</li>
<li><strong>Emission factors for degradation</strong>: Similar to deforestation, carbon emissions caused by forest degradation need to be estimated, with corresponding uncertainties.</li>
</ul></li>
<li><p><strong>Reference Scenarios</strong></p>
<ul>
<li><strong>Baseline scenario</strong>: The emission estimate in the reference scenario, i.e., the amount of carbon that would be released without the project intervention. This scenario is usually based on historical deforestation rates.</li>
<li><strong>Project scenario</strong>: The emission estimate with the REDD+ project intervention, where deforestation and degradation would be reduced.</li>
</ul></li>
<li><p><strong>Time Period (Horizon)</strong></p>
<ul>
<li><strong>Project duration</strong>: How many years the project will be monitored, affecting both annual and cumulative emissions.</li>
<li><strong>Time step</strong>: Whether the calculation is annual or over larger intervals, this also needs to be considered in the modeling.</li>
</ul></li>
<li><p><strong>Expected Results (Emission Reductions)</strong></p>
<ul>
<li><strong>Expected emission reductions (ton/year)</strong>: The expected result in terms of avoided carbon emissions per year or over the project’s total period.</li>
</ul></li>
<li><p><strong>Probability Distributions</strong></p></li>
</ol>
<ul>
<li><strong>Monte Carlo Simulations</strong>: The spreadsheet asks for probability distributions for different key variables (biomass, deforestation rate, emission factor, etc.), which are used to simulate multiple possible emission scenarios considering the uncertainties involved.</li>
</ul>
</section>
<section id="summary-of-tables-and-fields" class="level3" data-number="7.4.2">
<h3 data-number="7.4.2" class="anchored" data-anchor-id="summary-of-tables-and-fields"><span class="header-section-number">7.4.2</span> Summary of Tables and Fields</h3>
<p>The spreadsheet typically contains the following sections and fields:</p>
<ol type="1">
<li><strong>Project area data</strong>: Geographic information, forest area, deforested area, etc.</li>
<li><strong>Biomass</strong>: Above-ground biomass, with mean, standard deviation, and carbon conversion factor.</li>
<li><strong>Deforestation rate</strong>: Mean deforestation rate, probability distribution, and associated uncertainties.</li>
<li><strong>Emission factors</strong>: Carbon emission factors per hectare deforested.</li>
<li><strong>Monte Carlo simulations</strong>: Number of iterations for the simulation and the distributions for the variables involved.</li>
<li><strong>Estimated emission reductions</strong>: Simulation results, including mean avoided emissions and confidence intervals.</li>
</ol>
<p>For filling out the spreadsheet, detailed data on biomass, deforestation rates, emission factors, and the uncertainties associated with each of these variables were required. This was calculated by the contractor and is available in previous chapters. Biomass, deforestation rates, and emission factor data were the responsibility of the contractor to provide to the analysts.</p>
</section>
</section>
</section>
<section id="references" class="level1" data-number="8">
<h1 data-number="8"><span class="header-section-number">8</span> References</h1>
<p>Adami, M.; Mello, M. P.; Aguiar, D. A.; Rudorff, B. F. T.; Souza, A. F. de. A Web platform development to perform thematic accuracy assessment of sugarcane mapping in South-Central Brazil. Remote Sensing, v. 4, n.10, p.&nbsp;3201-3214, 2012.</p>
<p>P. Mayaux, H. Eva, J. Gallego, A. H. Strahler, M. Herold, S. Agrawal, et al., “Validation of the Global Land Cover 2000 Map,” IEEE Transactions on Geoscience and Remote Sensing, vol.&nbsp;44, no. 7, pp.&nbsp;1728–1739, Jul.&nbsp;2006</p>
<p>Olofsson, P., Foody, G. M., Herold, M., Stehman, S. V., Woodcock, C. E., &amp; Wulder, M. A. (2014). Good practices for estimating area and assessing accuracy of land change. Remote Sensing of Environment, 148, 42–57.</p>
<p>R. Dalagnol et al., “Mapping tropical forest degradation with deep learning and Planet NICFI data,” Remote Sensing of Environment, vol.&nbsp;298, 2023, Art. no. 113798.</p>
<p>Data was obtained from:</p>
<ul>
<li>Para_MRV_Dataset <a href="https://drive.google.com/drive/folders/1_T3i4s1FmSqOboPq1tvdGnxSqzwLnK7U?usp=sharing">https://drive.google.com/drive/folders/1_T3i4s1FmSqOboPq1tvdGnxSqzwLnK7U?usp=sharing</a></li>
<li>Para_MRV_Dataset_V2 <a href="https://drive.google.com/drive/folders/1xb53QVt5IAW6KoKMLUI2tsjxQWiW5o4n?usp=sharing">https://drive.google.com/drive/folders/1xb53QVt5IAW6KoKMLUI2tsjxQWiW5o4n?usp=sharing</a></li>
<li>Incertezas_Para <a href="https://drive.google.com/drive/folders/19jejosLTibwZPGpCTKs9_JkndWgdDwoG?usp=sharing">https://drive.google.com/drive/folders/19jejosLTibwZPGpCTKs9_JkndWgdDwoG?usp=sharing</a></li>
</ul>
</section>


<div id="quarto-appendix" class="default"><section id="footnotes" class="footnotes footnotes-end-of-document" role="doc-endnotes"><h2 class="anchored quarto-appendix-heading">Footnotes</h2>

<ol>
<li id="fn1"><p><strong>ART</strong> stands for Architecture for REDD+ Transactions and <strong>TREES</strong> is basically the standard protocol that all coalition stakeholders must follow in order to be eligible for REDD+ project activities and investments.<a href="#fnref1" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
<li id="fn2"><p><a href="https://www.artredd.org/wp-content/uploads/2021/12/MC-4-estimating-ER-from-forests-update-1-1.xlsx">https://www.artredd.org/wp-content/uploads/2021/12/MC-4-estimating-ER-from-forests-update-1-1.xlsx</a><a href="#fnref2" class="footnote-back" role="doc-backlink">↩︎</a></p></li>
</ol>
</section></div></main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const onCopySuccess = function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  }
  const getTextToCopy = function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
    text: getTextToCopy
  });
  clipboard.on('success', onCopySuccess);
  if (window.document.getElementById('quarto-embedded-source-code-modal')) {
    // For code content inside modals, clipBoardJS needs to be initialized with a container option
    // TODO: Check when it could be a function (https://github.com/zenorocha/clipboard.js/issues/860)
    const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
      text: getTextToCopy,
      container: window.document.getElementById('quarto-embedded-source-code-modal')
    });
    clipboardModal.on('success', onCopySuccess);
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->
<<<<<<< HEAD
<script>var lightboxQuarto = GLightbox({"selector":".lightbox","openEffect":"zoom","descPosition":"bottom","loop":false,"closeEffect":"zoom"});
=======
<script>var lightboxQuarto = GLightbox({"loop":false,"closeEffect":"zoom","openEffect":"zoom","selector":".lightbox","descPosition":"bottom"});
>>>>>>> 3c5bf33c1a81964c7f78ec05c7ff5ddc53bed5e7
(function() {
  let previousOnload = window.onload;
  window.onload = () => {
    if (previousOnload) {
      previousOnload();
    }
    lightboxQuarto.on('slide_before_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      const href = trigger.getAttribute('href');
      if (href !== null) {
        const imgEl = window.document.querySelector(`a[href="${href}"] img`);
        if (imgEl !== null) {
          const srcAttr = imgEl.getAttribute("src");
          if (srcAttr && srcAttr.startsWith("data:")) {
            slideConfig.href = srcAttr;
          }
        }
      } 
    });
  
    lightboxQuarto.on('slide_after_load', (data) => {
      const { slideIndex, slideNode, slideConfig, player, trigger } = data;
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(slideNode);
      }
    });
  
  };
  
})();
          </script>




</body></html>